/* Pinch engine: window.AlibiPinch. One classic script, no modules, safe to concatenate into the design-system bundle.

   AlibiPinch.mount(el, {size=96, mood='idle', theme='auto'|'dark'|'light', still=false, rim=false, seed, ambient=false}) -> inst
     ambient: true gives a visible instance some life of its own: four short fidgets (inspect,
                                    perk, glance, click) layered under any clip, only in mood idle, first 6-10 s after
                                    mount then one every 14-28 s (seeded), and no 2-minute rest while visible. Never with
                                    still, reduced motion, a glyph size or Quiet lobster (localStorage alibi.quiet = "1").
                                    inst.ambient(on) switches it; inst.state().fidget names the one playing (or null).
     inst.set(mood)                 held/looping mood, crossfaded over 420 ms
     inst.play(clip, {force, chain}) -> Promise<boolean>  true when it played to the end; false when dropped or pre-empted.
                                    Priority + 90 s cooldown: a higher priority clip pre-empts, equal or lower is dropped.
                                    force bypasses cooldown, priority and the 3-sideeyes cap. sideeye chains nudge unless chain:false.
     inst.lookAt(x, y)              -1..1 gaze offset, smoothed; lookAt(null) lets go
     inst.seek(moodOrClip, ms)      deterministic frame (seeded blinks and idle gaze); holds until set/play/resume
     inst.setSize(px)               LOD by rendered size: >=96 full, 40-95 no legs, 24-39 lod24, 20-23 lod20, <20 lod16
     inst.destroy()
     extras: inst.camera(on) (lens glow = max(camera, clip)), inst.theme(theme, rim), inst.pose(params|null) (held pose layer),
             inst.resume(), inst.state(), inst.frame() (last rendered params), inst.el
   AlibiPinch.svg({size, mood|clip, ms, theme, camera}) -> static SVG markup (no argument: pinch.svg byte for byte)
   AlibiPinch.moods, AlibiPinch.clips, AlibiPinch.params, AlibiPinch.duration(name), AlibiPinch.reducedMotion([bool|null])

   Layers per frame (clips.json policy.composition): neutral <- held pose <- mood loop (bodySquash multiplies,
   numbers add) <- gaze + lookAt <- one-shot clip (absolute). Blink multiplies eyeOpen. Every discontinuity (clip in 120 ms,
   clip out 240 ms, mood 420 ms, wake 260 ms) crossfades from the last rendered frame. Still mode, reduced motion and the
   16/20 px glyphs never run rAF: they show key poses and crossfade a ghost copy over 200 ms. One shared rAF drives every
   instance; it stops when the tab is hidden, an instance is off-screen, or after 2 min without input (rests on the key pose).
   Per frame only attributes change (cached, written when different). */
(function (root) {
  'use strict';
  /* @pinch-data:begin */
  /* Generated by build.mjs from pinch.svg, pinch-lod24/20/16.svg, rig.json, clips.json and rig.js. Do not edit by hand. */
  var SVG = {"full":"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 160 160\" class=\"pinch theme-auto\" role=\"img\" aria-label=\"Pinch, a green detective lobster holding a magnifying lens\"><style>\n[data-theme=dark]{--pinch-ol-auto:transparent;--pinch-glint-auto:var(--pinch-shine,#FFF)}\n[data-theme=light]{--pinch-ol-auto:var(--pinch-outline,#365900);--pinch-glint-auto:var(--pinch-shade,#588C05)}\n@media (prefers-color-scheme:dark){:root:not([data-theme]){--pinch-ol-auto:transparent;--pinch-glint-auto:var(--pinch-shine,#FFF)}}\n.pinch{--p-ol:var(--pinch-ol-auto,var(--pinch-outline,#365900));--p-glint:var(--pinch-glint-auto,var(--pinch-shade,#588C05));overflow:visible}\n.pinch.on-dark{--p-ol:transparent;--p-glint:var(--pinch-shine,#FFF)}\n.pinch.on-light{--p-ol:var(--pinch-outline,#365900);--p-glint:var(--pinch-shade,#588C05)}\n.pinch.rim{--p-ol:var(--pinch-outline,#8FD400)}\n.pinch .o{stroke:var(--p-ol);stroke-width:calc(2*var(--pinch-ow,3));paint-order:stroke;stroke-linejoin:round}\n.pinch .u{fill:none;stroke:var(--p-ol);stroke-linecap:round}\n.pinch .k{fill:none;stroke-linecap:round;stroke-linejoin:round}\n.pinch .fb{fill:var(--pinch-body,#76B900)}.pinch .fy{fill:var(--pinch-belly,#97DC42)}.pinch .fs{fill:var(--pinch-shade,#588C05)}\n.pinch .fe{fill:var(--pinch-eye,#000)}.pinch .fw{fill:var(--pinch-shine,#FFF)}\n.pinch .sb{stroke:var(--pinch-body,#76B900)}.pinch .ss{stroke:var(--pinch-shade,#588C05)}.pinch .se{stroke:var(--pinch-eye,#000)}\n.pinch .sy{stroke:var(--pinch-belly,#97DC42)}\n.pinch .fl{fill:var(--pinch-lens,#D7D7D7)}.pinch .sl{stroke:var(--pinch-lens,#D7D7D7)}\n@container pinch (max-width:79px){.pinch{--pinch-ow:3.6}}\n@container pinch (max-width:39px){.pinch{--pinch-ow:5.5}}\n@container pinch (max-width:95px){.pinch .lod-96{display:none}}\n@container pinch (max-width:39px){.pinch .lod-40{display:none}}\n@media (max-width:79px){.pinch:root{--pinch-ow:3.6}}\n@media (max-width:39px){.pinch:root{--pinch-ow:5.5}}\n@media (max-width:95px){.pinch:root .lod-96{display:none}}\n@media (max-width:39px){.pinch:root .lod-40{display:none}}\n.pinch[data-lod=\"56\"]{--pinch-ow:3.6}.pinch[data-lod=\"28\"]{--pinch-ow:5.5}\n.pinch[data-lod=\"56\"] .lod-96,.pinch[data-lod=\"28\"] .lod-96,.pinch[data-lod=\"28\"] .lod-40{display:none}\n</style><defs><radialGradient id=\"pinch-bloom\"><stop offset=\"0\" style=\"stop-color:var(--bloom,rgba(118,185,0,.35))\"/><stop offset=\"1\" style=\"stop-color:var(--bloom,rgba(118,185,0,.35));stop-opacity:0\"/></radialGradient><clipPath id=\"pinch-body-clip\"><path d=\"M80 33A26 26 0 0 0 57.25 46.41A150 150 0 0 0 38.5 117.18A26 26 0 0 0 64.5 143.5H95.5A26 26 0 0 0 121.5 117.18A150 150 0 0 0 102.75 46.41A26 26 0 0 0 80 33Z\"/></clipPath></defs><circle id=\"bloom\" data-part=\"bloom\" cx=\"80\" cy=\"86\" r=\"76\" fill=\"url(#pinch-bloom)\" opacity=\"0\"/><g id=\"pinch-root\" data-part=\"pinch-root\"><g id=\"tail\" data-part=\"tail\" class=\"lod-40\"><path class=\"o fs\" d=\"M35 138Q36.25 126.85 25.97 128.65Q23.82 138.86 35 138Z\"/><path class=\"o fs\" d=\"M35 138Q28.21 127.03 20.15 135.91Q25.45 146.68 35 138Z\"/><path class=\"o fs\" d=\"M35 138Q24.49 134.09 23.74 144.5Q33.13 149.06 35 138Z\"/><path class=\"u\" d=\"M48 133L38 138\" style=\"stroke-width:calc(11 + 2*var(--pinch-ow,3))\"/><path class=\"k ss\" d=\"M48 133L38 138\" stroke-width=\"11\"/><path class=\"k sb lod-96\" d=\"M41.5 128.2q-1.2 5 0 10.2\" stroke-width=\"1.8\" opacity=\".55\"/></g><g id=\"legs\" data-part=\"legs\" class=\"lod-96\"><path class=\"u\" d=\"M63.5 136L60 147\" style=\"stroke-width:calc(7 + 2*var(--pinch-ow,3))\"/><path class=\"k ss\" d=\"M63.5 136L60 147\" stroke-width=\"7\"/><path class=\"u\" d=\"M73 139.5L71.5 149\" style=\"stroke-width:calc(7 + 2*var(--pinch-ow,3))\"/><path class=\"k ss\" d=\"M73 139.5L71.5 149\" stroke-width=\"7\"/><path class=\"u\" d=\"M87 139.5L88.5 149\" style=\"stroke-width:calc(7 + 2*var(--pinch-ow,3))\"/><path class=\"k ss\" d=\"M87 139.5L88.5 149\" stroke-width=\"7\"/><path class=\"u\" d=\"M96.5 136L100 147\" style=\"stroke-width:calc(7 + 2*var(--pinch-ow,3))\"/><path class=\"k ss\" d=\"M96.5 136L100 147\" stroke-width=\"7\"/></g><g id=\"body\" data-part=\"body\"><g id=\"antenna-l\" data-part=\"antenna-l\"><path class=\"u\" d=\"M74.5 38C72.6 26 65 16.6 54.2 12.6C46.6 9.8 39.6 11.6 38.4 17\" style=\"stroke-width:calc(3.4 + 2*var(--pinch-ow,3))\"/><path class=\"k sb\" d=\"M74.5 38C72.6 26 65 16.6 54.2 12.6C46.6 9.8 39.6 11.6 38.4 17\" stroke-width=\"3.4\"/></g><g id=\"antenna-r\" data-part=\"antenna-r\"><path class=\"u\" d=\"M85.5 38C87.4 26 95 16.6 105.8 12.6C113.4 9.8 120.4 11.6 121.6 17\" style=\"stroke-width:calc(3.4 + 2*var(--pinch-ow,3))\"/><path class=\"k sb\" d=\"M85.5 38C87.4 26 95 16.6 105.8 12.6C113.4 9.8 120.4 11.6 121.6 17\" stroke-width=\"3.4\"/></g><path class=\"o fb\" d=\"M80 33A26 26 0 0 0 57.25 46.41A150 150 0 0 0 38.5 117.18A26 26 0 0 0 64.5 143.5H95.5A26 26 0 0 0 121.5 117.18A150 150 0 0 0 102.75 46.41A26 26 0 0 0 80 33Z\"/><g clip-path=\"url(#pinch-body-clip)\"><path class=\"fs\" fill-rule=\"evenodd\" d=\"M20 20H140V160H20ZM11 84a62 62 0 1 0 124 0a62 62 0 1 0 -124 0Z\"/></g><path class=\"k sy lod-40\" d=\"M64.31 53.9A16.5 16.5 0 0 1 73.29 43.93\" stroke-width=\"4.4\"/><g id=\"belly\" data-part=\"belly\"><ellipse class=\"fy\" cx=\"80\" cy=\"122.5\" rx=\"23\" ry=\"18\"/><path class=\"k ss lod-40\" d=\"M60.93 118Q80 121.6 99.07 118\" stroke-width=\"2.2\"/><path class=\"k ss lod-40\" d=\"M62.01 129.5Q80 133.1 97.99 129.5\" stroke-width=\"2.2\"/></g><g id=\"blush\" data-part=\"blush\" class=\"lod-40\" style=\"fill:var(--pinch-blush,rgba(242,169,0,.35))\" opacity=\"0\"><ellipse cx=\"52.5\" cy=\"94.5\" rx=\"6\" ry=\"3.6\"/><ellipse cx=\"107.5\" cy=\"94.5\" rx=\"6\" ry=\"3.6\"/></g><g id=\"eye-l\" data-part=\"eye-l\"><clipPath id=\"pinch-eye-clip-l\"><ellipse cx=\"66\" cy=\"80\" rx=\"10.2\" ry=\"12\"/></clipPath><g data-part=\"eye-l-open\"><ellipse class=\"fe\" cx=\"66\" cy=\"80\" rx=\"9.4\" ry=\"11.2\"/><circle class=\"fw\" cx=\"62.9\" cy=\"75.6\" r=\"2.9\"/><g clip-path=\"url(#pinch-eye-clip-l)\"><g id=\"lid-l\" data-part=\"lid-l\"><path class=\"fb\" d=\"M53.6 48H78.4V66Q66 69.2 53.6 66Z\"/><path class=\"k ss\" data-part=\"lid-l-lash\" d=\"M55.1 66.3Q66 69.5 76.9 66.3\" stroke-width=\"2\" opacity=\"0\"/></g></g></g><path class=\"k se\" data-part=\"eye-l-joy\" d=\"M58.8 82.6Q66 70.6 73.2 82.6\" stroke-width=\"4\" opacity=\"0\"/></g><g id=\"eye-r\" data-part=\"eye-r\"><clipPath id=\"pinch-eye-clip-r\"><ellipse cx=\"94\" cy=\"80\" rx=\"10.2\" ry=\"12\"/></clipPath><g data-part=\"eye-r-open\"><ellipse class=\"fe\" cx=\"94\" cy=\"80\" rx=\"9.4\" ry=\"11.2\"/><circle class=\"fw\" cx=\"90.9\" cy=\"75.6\" r=\"2.9\"/><g clip-path=\"url(#pinch-eye-clip-r)\"><g id=\"lid-r\" data-part=\"lid-r\"><path class=\"fb\" d=\"M81.6 48H106.4V66Q94 69.2 81.6 66Z\"/><path class=\"k ss\" data-part=\"lid-r-lash\" d=\"M83.1 66.3Q94 69.5 104.9 66.3\" stroke-width=\"2\" opacity=\"0\"/></g></g></g><path class=\"k se\" data-part=\"eye-r-joy\" d=\"M86.8 82.6Q94 70.6 101.2 82.6\" stroke-width=\"4\" opacity=\"0\"/></g><g id=\"mouth\" data-part=\"mouth\"><path class=\"k se\" data-part=\"mouth-smile\" d=\"M74.4 95.4Q80 101.2 85.6 95.4\" stroke-width=\"2.6\"/><path class=\"k se\" data-part=\"mouth-flat\" d=\"M75.4 97H84.6\" stroke-width=\"2.6\" opacity=\"0\"/><path class=\"fe\" data-part=\"mouth-open\" d=\"M73.2 94.6H86.8Q86.8 105 80 105Q73.2 105 73.2 94.6Z\" opacity=\"0\"/><ellipse class=\"fe\" data-part=\"mouth-o\" cx=\"80\" cy=\"98\" rx=\"3.2\" ry=\"3.9\" opacity=\"0\"/></g></g><g id=\"arm-l\" data-part=\"arm-l\"><path class=\"u\" d=\"M51.5 104.5L31.5 89\" style=\"stroke-width:calc(9 + 2*var(--pinch-ow,3))\"/><path class=\"k ss\" d=\"M51.5 104.5L31.5 89\" stroke-width=\"9\"/><g id=\"claw-l\" data-part=\"claw-l\"><g transform=\"translate(31.5 89) rotate(-24) scale(1.12 1.12)\"><g id=\"jaw-l-bottom\" data-part=\"jaw-l-bottom\"><path class=\"o fb\" d=\"M12.6 -17.5A36.3 36.3 0 0 0 7.64 -43.78A2.6 2.6 0 0 0 2.7 -42.17A23.04 23.04 0 0 1 3.2 -25.5L1.5 -18Z\"/></g><g id=\"jaw-l-top\" data-part=\"jaw-l-top\"><path class=\"o fb\" d=\"M-12.6 -17.5A36.3 36.3 0 0 1 -7.64 -43.78A2.6 2.6 0 0 1 -2.7 -42.17A23.04 23.04 0 0 0 -3.2 -25.5L-1.5 -18Z\"/></g><circle class=\"o fb\" cx=\"0\" cy=\"-14\" r=\"13\"/><path class=\"fs lod-40\" d=\"M-12.4 -11A13 13 0 0 0 12.4 -11A19.5 19.5 0 0 1 -12.4 -11Z\"/></g><g id=\"paper\" data-part=\"paper\" opacity=\"0\"><g transform=\"rotate(40 13.28 48.07)\"><rect class=\"o fw\" x=\"0.28\" y=\"38.57\" width=\"26\" height=\"19\" rx=\"2.6\"/><path class=\"k ss\" d=\"M4.78 44.07h15\" stroke-width=\"1.8\"/><path class=\"k ss\" d=\"M4.78 48.37h17\" stroke-width=\"1.8\"/><path class=\"k ss\" d=\"M4.78 52.67h10\" stroke-width=\"1.8\"/></g></g></g></g><g id=\"arm-r\" data-part=\"arm-r\"><path class=\"u\" d=\"M108 105L125.5 115\" style=\"stroke-width:calc(9 + 2*var(--pinch-ow,3))\"/><path class=\"k ss\" d=\"M108 105L125.5 115\" stroke-width=\"9\"/><g id=\"claw-r\" data-part=\"claw-r\"><g transform=\"translate(125.5 115) rotate(14) scale(-0.86 0.86)\"><g id=\"jaw-r-bottom\" data-part=\"jaw-r-bottom\"><path class=\"o fb\" d=\"M12.6 -17.5A36.3 36.3 0 0 0 7.64 -43.78A2.6 2.6 0 0 0 2.7 -42.17A23.04 23.04 0 0 1 3.2 -25.5L1.5 -18Z\"/></g></g><g id=\"lens\" data-part=\"lens\"><path class=\"u\" d=\"M127.22 105.68L136.17 76.42\" style=\"stroke-width:calc(5 + 2*var(--pinch-ow,3))\"/><path class=\"k sl\" d=\"M127.22 105.68L136.17 76.42\" stroke-width=\"5\"/><path class=\"k se\" d=\"M127.22 105.68L136.17 76.42\" stroke-width=\"5\" opacity=\".42\"/><path class=\"k sl\" d=\"M136.72 74.6L135.73 77.86\" stroke-width=\"7.4\" style=\"stroke-linecap:butt\"/><g id=\"lens-glow\" data-part=\"lens-glow\"><circle class=\"k sb\" data-part=\"lens-ring\" cx=\"140.73\" cy=\"61.5\" r=\"17.1\" stroke-width=\"2.6\" opacity=\"0\"/><circle data-part=\"lens-wash\" cx=\"140.73\" cy=\"61.5\" r=\"12.5\" style=\"fill:var(--pinch-lens-glow,rgba(170,240,89,.55))\" opacity=\"0\"/></g><clipPath id=\"pinch-glass-clip\"><circle cx=\"140.73\" cy=\"61.5\" r=\"12.1\"/></clipPath><g clip-path=\"url(#pinch-glass-clip)\"><g id=\"lens-view\" data-part=\"lens-view\" opacity=\"0\"><circle class=\"fb\" cx=\"140.73\" cy=\"61.5\" r=\"13.5\"/><g id=\"lens-eye\" data-part=\"lens-eye\"><clipPath id=\"pinch-lens-eye-clip\"><ellipse cx=\"94\" cy=\"80\" rx=\"10.2\" ry=\"12\"/></clipPath><g data-part=\"lens-eye-r-open\"><ellipse class=\"fe\" cx=\"94\" cy=\"80\" rx=\"9.4\" ry=\"11.2\"/><circle class=\"fw\" cx=\"90.9\" cy=\"75.6\" r=\"2.9\"/><g clip-path=\"url(#pinch-lens-eye-clip)\"><g id=\"lens-lid\" data-part=\"lens-lid\"><path class=\"fb\" d=\"M81.6 48H106.4V66Q94 69.2 81.6 66Z\"/><path class=\"k ss\" data-part=\"lens-lid-lash\" d=\"M83.1 66.3Q94 69.5 104.9 66.3\" stroke-width=\"2\" opacity=\"0\"/></g></g></g></g></g></g><g clip-path=\"url(#pinch-glass-clip)\"><g id=\"lens-sweep\" data-part=\"lens-sweep\" opacity=\"0\"><path class=\"k\" style=\"stroke:var(--pinch-spark,#AAF059)\" d=\"M129.48 50.25L151.98 72.75\" stroke-width=\"5\"/></g></g><circle class=\"u\" cx=\"140.73\" cy=\"61.5\" r=\"13.4\" style=\"stroke-width:calc(2.2 + 2*var(--pinch-ow,3))\"/><circle class=\"k sl\" cx=\"140.73\" cy=\"61.5\" r=\"12.5\" stroke-width=\"4\"/><g id=\"lens-glint\" data-part=\"lens-glint\"><path class=\"k\" style=\"stroke:var(--p-glint)\" d=\"M133.13 59.32A7.9 7.9 0 0 1 136.54 54.8\" stroke-width=\"2.4\" stroke-opacity=\".7\"/><path class=\"k\" style=\"stroke:var(--p-glint)\" d=\"M143.69 54.18A7.9 7.9 0 0 1 145.37 55.11\" stroke-width=\"2.4\" stroke-opacity=\".7\"/></g></g><g transform=\"translate(125.5 115) rotate(14) scale(-0.86 0.86)\"><g id=\"jaw-r-top\" data-part=\"jaw-r-top\"><path class=\"o fb\" d=\"M-12.6 -17.5A36.3 36.3 0 0 1 -7.64 -43.78A2.6 2.6 0 0 1 -2.7 -42.17A23.04 23.04 0 0 0 -3.2 -25.5L-1.5 -18Z\"/></g><circle class=\"o fb\" cx=\"0\" cy=\"-14\" r=\"13\"/><path class=\"fs lod-40\" d=\"M-12.4 -11A13 13 0 0 0 12.4 -11A19.5 19.5 0 0 1 -12.4 -11Z\"/></g></g></g><g id=\"sweat\" data-part=\"sweat\" opacity=\"0\"><path style=\"fill:var(--pinch-lens,#D7D7D7)\" d=\"M60.5 50C62.9 54 64.9 55.8 64.9 58.4A4.4 4.4 0 0 1 56.1 58.4C56.1 55.8 58.1 54 60.5 50Z\"/><path class=\"k\" style=\"stroke:var(--pinch-shine,#FFF)\" d=\"M58.3 58a2.4 2.4 0 0 0 1.8 2.2\" stroke-width=\"1.3\"/></g><g id=\"zzz\" data-part=\"zzz\" opacity=\"0\"><path data-part=\"z0\" class=\"k ss\" d=\"M112 36h5l-5 5h5\" stroke-width=\"1.6\"/><path data-part=\"z1\" class=\"k ss\" d=\"M121 25h6.5l-6.5 6.5h6.5\" stroke-width=\"1.95\"/><path data-part=\"z2\" class=\"k ss\" d=\"M131 12h8l-8 8h8\" stroke-width=\"2.3\"/></g></g><g id=\"sparkle\" data-part=\"sparkle\" opacity=\"0\"><path data-part=\"spark0\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M14 23Q15.4 28.6 21 30Q15.4 31.4 14 37Q12.6 31.4 7 30Q12.6 28.6 14 23Z\"/><path data-part=\"spark1\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M146 23Q147.4 28.6 153 30Q147.4 31.4 146 37Q144.6 31.4 139 30Q144.6 28.6 146 23Z\"/><path data-part=\"spark2\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M27 8.8Q27.84 12.16 31.2 13Q27.84 13.84 27 17.2Q26.16 13.84 22.8 13Q26.16 12.16 27 8.8Z\"/><path data-part=\"spark3\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M133 7.8Q133.84 11.16 137.2 12Q133.84 12.84 133 16.2Q132.16 12.84 128.8 12Q132.16 11.16 133 7.8Z\"/><path data-part=\"spark4\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M6 54.4Q6.72 57.28 9.6 58Q6.72 58.72 6 61.6Q5.28 58.72 2.4 58Q5.28 57.28 6 54.4Z\"/><path data-part=\"spark5\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M154 54.4Q154.72 57.28 157.6 58Q154.72 58.72 154 61.6Q153.28 58.72 150.4 58Q153.28 57.28 154 54.4Z\"/></g></svg>\n","lod24":"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 160 160\" class=\"pinch theme-auto\" role=\"img\" aria-label=\"Pinch, a green detective lobster holding a magnifying lens\"><style>\n[data-theme=dark]{--pinch-ol-auto:transparent;--pinch-glint-auto:var(--pinch-shine,#FFF)}\n[data-theme=light]{--pinch-ol-auto:var(--pinch-outline,#365900);--pinch-glint-auto:var(--pinch-shade,#588C05)}\n@media (prefers-color-scheme:dark){:root:not([data-theme]){--pinch-ol-auto:transparent;--pinch-glint-auto:var(--pinch-shine,#FFF)}}\n.pinch{--p-ol:var(--pinch-ol-auto,var(--pinch-outline,#365900));--p-glint:var(--pinch-glint-auto,var(--pinch-shade,#588C05));overflow:visible}\n.pinch.on-dark{--p-ol:transparent;--p-glint:var(--pinch-shine,#FFF)}\n.pinch.on-light{--p-ol:var(--pinch-outline,#365900);--p-glint:var(--pinch-shade,#588C05)}\n.pinch.rim{--p-ol:var(--pinch-outline,#8FD400)}\n.pinch .o{stroke:var(--p-ol);stroke-width:calc(2*var(--pinch-ow,3));paint-order:stroke;stroke-linejoin:round}\n.pinch .u{fill:none;stroke:var(--p-ol);stroke-linecap:round}\n.pinch .k{fill:none;stroke-linecap:round;stroke-linejoin:round}\n.pinch .fb{fill:var(--pinch-body,#76B900)}.pinch .fy{fill:var(--pinch-belly,#97DC42)}.pinch .fs{fill:var(--pinch-shade,#588C05)}\n.pinch .fe{fill:var(--pinch-eye,#000)}.pinch .fw{fill:var(--pinch-shine,#FFF)}\n.pinch .sb{stroke:var(--pinch-body,#76B900)}.pinch .ss{stroke:var(--pinch-shade,#588C05)}.pinch .se{stroke:var(--pinch-eye,#000)}\n.pinch .sy{stroke:var(--pinch-belly,#97DC42)}\n.pinch .fl{fill:var(--pinch-lens,#D7D7D7)}.pinch .sl{stroke:var(--pinch-lens,#D7D7D7)}\n@container pinch (max-width:79px){.pinch{--pinch-ow:3.6}}\n@container pinch (max-width:39px){.pinch{--pinch-ow:5.5}}\n@container pinch (max-width:95px){.pinch .lod-96{display:none}}\n@container pinch (max-width:39px){.pinch .lod-40{display:none}}\n@media (max-width:79px){.pinch:root{--pinch-ow:3.6}}\n@media (max-width:39px){.pinch:root{--pinch-ow:5.5}}\n@media (max-width:95px){.pinch:root .lod-96{display:none}}\n@media (max-width:39px){.pinch:root .lod-40{display:none}}\n.pinch[data-lod=\"56\"]{--pinch-ow:3.6}.pinch[data-lod=\"28\"]{--pinch-ow:5.5}\n.pinch[data-lod=\"56\"] .lod-96,.pinch[data-lod=\"28\"] .lod-96,.pinch[data-lod=\"28\"] .lod-40{display:none}\n</style><defs><radialGradient id=\"pinch-bloom\"><stop offset=\"0\" style=\"stop-color:var(--bloom,rgba(118,185,0,.35))\"/><stop offset=\"1\" style=\"stop-color:var(--bloom,rgba(118,185,0,.35));stop-opacity:0\"/></radialGradient><clipPath id=\"pinch-body-clip\"><path d=\"M80 33A26 26 0 0 0 57.25 46.41A150 150 0 0 0 38.5 117.18A26 26 0 0 0 64.5 143.5H95.5A26 26 0 0 0 121.5 117.18A150 150 0 0 0 102.75 46.41A26 26 0 0 0 80 33Z\"/></clipPath></defs><circle id=\"bloom\" data-part=\"bloom\" cx=\"80\" cy=\"86\" r=\"76\" fill=\"url(#pinch-bloom)\" opacity=\"0\"/><g id=\"pinch-root\" data-part=\"pinch-root\"><g id=\"body\" data-part=\"body\"><g id=\"antenna-l\" data-part=\"antenna-l\"><path class=\"u\" d=\"M74.5 38C72.6 26 65 16.6 54.2 12.6C46.6 9.8 39.6 11.6 38.4 17\" style=\"stroke-width:calc(3.4 + 2*var(--pinch-ow,3))\"/><path class=\"k sb\" d=\"M74.5 38C72.6 26 65 16.6 54.2 12.6C46.6 9.8 39.6 11.6 38.4 17\" stroke-width=\"3.4\"/></g><g id=\"antenna-r\" data-part=\"antenna-r\"><path class=\"u\" d=\"M85.5 38C87.4 26 95 16.6 105.8 12.6C113.4 9.8 120.4 11.6 121.6 17\" style=\"stroke-width:calc(3.4 + 2*var(--pinch-ow,3))\"/><path class=\"k sb\" d=\"M85.5 38C87.4 26 95 16.6 105.8 12.6C113.4 9.8 120.4 11.6 121.6 17\" stroke-width=\"3.4\"/></g><path class=\"o fb\" d=\"M80 33A26 26 0 0 0 57.25 46.41A150 150 0 0 0 38.5 117.18A26 26 0 0 0 64.5 143.5H95.5A26 26 0 0 0 121.5 117.18A150 150 0 0 0 102.75 46.41A26 26 0 0 0 80 33Z\"/><g clip-path=\"url(#pinch-body-clip)\"><path class=\"fs\" fill-rule=\"evenodd\" d=\"M20 20H140V160H20ZM11 84a62 62 0 1 0 124 0a62 62 0 1 0 -124 0Z\"/></g><g id=\"belly\" data-part=\"belly\"><ellipse class=\"fy\" cx=\"80\" cy=\"122.5\" rx=\"23\" ry=\"18\"/></g><g id=\"eye-l\" data-part=\"eye-l\"><clipPath id=\"pinch-eye-clip-l\"><ellipse cx=\"66\" cy=\"80\" rx=\"10.2\" ry=\"12\"/></clipPath><g data-part=\"eye-l-open\"><ellipse class=\"fe\" cx=\"66\" cy=\"80\" rx=\"9.4\" ry=\"11.2\"/><circle class=\"fw\" cx=\"62.9\" cy=\"75.6\" r=\"2.9\"/><g clip-path=\"url(#pinch-eye-clip-l)\"><g id=\"lid-l\" data-part=\"lid-l\"><path class=\"fb\" d=\"M53.6 48H78.4V66Q66 69.2 53.6 66Z\"/><path class=\"k ss\" data-part=\"lid-l-lash\" d=\"M55.1 66.3Q66 69.5 76.9 66.3\" stroke-width=\"2\" opacity=\"0\"/></g></g></g><path class=\"k se\" data-part=\"eye-l-joy\" d=\"M58.8 82.6Q66 70.6 73.2 82.6\" stroke-width=\"4\" opacity=\"0\"/></g><g id=\"eye-r\" data-part=\"eye-r\"><clipPath id=\"pinch-eye-clip-r\"><ellipse cx=\"94\" cy=\"80\" rx=\"10.2\" ry=\"12\"/></clipPath><g data-part=\"eye-r-open\"><ellipse class=\"fe\" cx=\"94\" cy=\"80\" rx=\"9.4\" ry=\"11.2\"/><circle class=\"fw\" cx=\"90.9\" cy=\"75.6\" r=\"2.9\"/><g clip-path=\"url(#pinch-eye-clip-r)\"><g id=\"lid-r\" data-part=\"lid-r\"><path class=\"fb\" d=\"M81.6 48H106.4V66Q94 69.2 81.6 66Z\"/><path class=\"k ss\" data-part=\"lid-r-lash\" d=\"M83.1 66.3Q94 69.5 104.9 66.3\" stroke-width=\"2\" opacity=\"0\"/></g></g></g><path class=\"k se\" data-part=\"eye-r-joy\" d=\"M86.8 82.6Q94 70.6 101.2 82.6\" stroke-width=\"4\" opacity=\"0\"/></g><g id=\"mouth\" data-part=\"mouth\"><path class=\"k se\" data-part=\"mouth-smile\" d=\"M74.4 95.4Q80 101.2 85.6 95.4\" stroke-width=\"2.6\"/><path class=\"k se\" data-part=\"mouth-flat\" d=\"M75.4 97H84.6\" stroke-width=\"2.6\" opacity=\"0\"/><path class=\"fe\" data-part=\"mouth-open\" d=\"M73.2 94.6H86.8Q86.8 105 80 105Q73.2 105 73.2 94.6Z\" opacity=\"0\"/><ellipse class=\"fe\" data-part=\"mouth-o\" cx=\"80\" cy=\"98\" rx=\"3.2\" ry=\"3.9\" opacity=\"0\"/></g></g><g id=\"arm-l\" data-part=\"arm-l\"><path class=\"u\" d=\"M51.5 104.5L31.5 89\" style=\"stroke-width:calc(9 + 2*var(--pinch-ow,3))\"/><path class=\"k ss\" d=\"M51.5 104.5L31.5 89\" stroke-width=\"9\"/><g id=\"claw-l\" data-part=\"claw-l\"><g transform=\"translate(31.5 89) rotate(-24) scale(1.12 1.12)\"><g id=\"jaw-l-bottom\" data-part=\"jaw-l-bottom\"><path class=\"o fb\" d=\"M12.6 -17.5A36.3 36.3 0 0 0 7.64 -43.78A2.6 2.6 0 0 0 2.7 -42.17A23.04 23.04 0 0 1 3.2 -25.5L1.5 -18Z\"/></g><g id=\"jaw-l-top\" data-part=\"jaw-l-top\"><path class=\"o fb\" d=\"M-12.6 -17.5A36.3 36.3 0 0 1 -7.64 -43.78A2.6 2.6 0 0 1 -2.7 -42.17A23.04 23.04 0 0 0 -3.2 -25.5L-1.5 -18Z\"/></g><circle class=\"o fb\" cx=\"0\" cy=\"-14\" r=\"13\"/><path class=\"fs lod-40\" d=\"M-12.4 -11A13 13 0 0 0 12.4 -11A19.5 19.5 0 0 1 -12.4 -11Z\"/></g><g id=\"paper\" data-part=\"paper\" opacity=\"0\"><g transform=\"rotate(40 13.28 48.07)\"><rect class=\"o fw\" x=\"0.28\" y=\"38.57\" width=\"26\" height=\"19\" rx=\"2.6\"/><path class=\"k ss\" d=\"M4.78 44.07h15\" stroke-width=\"1.8\"/><path class=\"k ss\" d=\"M4.78 48.37h17\" stroke-width=\"1.8\"/><path class=\"k ss\" d=\"M4.78 52.67h10\" stroke-width=\"1.8\"/></g></g></g></g><g id=\"arm-r\" data-part=\"arm-r\"><path class=\"u\" d=\"M108 105L125.5 115\" style=\"stroke-width:calc(9 + 2*var(--pinch-ow,3))\"/><path class=\"k ss\" d=\"M108 105L125.5 115\" stroke-width=\"9\"/><g id=\"claw-r\" data-part=\"claw-r\"><g transform=\"translate(125.5 115) rotate(14) scale(-0.86 0.86)\"><g id=\"jaw-r-bottom\" data-part=\"jaw-r-bottom\"><path class=\"o fb\" d=\"M12.6 -17.5A36.3 36.3 0 0 0 7.64 -43.78A2.6 2.6 0 0 0 2.7 -42.17A23.04 23.04 0 0 1 3.2 -25.5L1.5 -18Z\"/></g></g><g id=\"lens\" data-part=\"lens\"><path class=\"u\" d=\"M127.22 105.68L136.17 76.42\" style=\"stroke-width:calc(5 + 2*var(--pinch-ow,3))\"/><path class=\"k sl\" d=\"M127.22 105.68L136.17 76.42\" stroke-width=\"5\"/><path class=\"k se\" d=\"M127.22 105.68L136.17 76.42\" stroke-width=\"5\" opacity=\".42\"/><path class=\"k sl\" d=\"M136.72 74.6L135.73 77.86\" stroke-width=\"7.4\" style=\"stroke-linecap:butt\"/><g id=\"lens-glow\" data-part=\"lens-glow\"><circle class=\"k sb\" data-part=\"lens-ring\" cx=\"140.73\" cy=\"61.5\" r=\"17.1\" stroke-width=\"2.6\" opacity=\"0\"/><circle data-part=\"lens-wash\" cx=\"140.73\" cy=\"61.5\" r=\"12.5\" style=\"fill:var(--pinch-lens-glow,rgba(170,240,89,.55))\" opacity=\"0\"/></g><clipPath id=\"pinch-glass-clip\"><circle cx=\"140.73\" cy=\"61.5\" r=\"12.1\"/></clipPath><g clip-path=\"url(#pinch-glass-clip)\"><g id=\"lens-view\" data-part=\"lens-view\" opacity=\"0\"><circle class=\"fb\" cx=\"140.73\" cy=\"61.5\" r=\"13.5\"/><g id=\"lens-eye\" data-part=\"lens-eye\"><clipPath id=\"pinch-lens-eye-clip\"><ellipse cx=\"94\" cy=\"80\" rx=\"10.2\" ry=\"12\"/></clipPath><g data-part=\"lens-eye-r-open\"><ellipse class=\"fe\" cx=\"94\" cy=\"80\" rx=\"9.4\" ry=\"11.2\"/><circle class=\"fw\" cx=\"90.9\" cy=\"75.6\" r=\"2.9\"/><g clip-path=\"url(#pinch-lens-eye-clip)\"><g id=\"lens-lid\" data-part=\"lens-lid\"><path class=\"fb\" d=\"M81.6 48H106.4V66Q94 69.2 81.6 66Z\"/><path class=\"k ss\" data-part=\"lens-lid-lash\" d=\"M83.1 66.3Q94 69.5 104.9 66.3\" stroke-width=\"2\" opacity=\"0\"/></g></g></g></g></g></g><g clip-path=\"url(#pinch-glass-clip)\"><g id=\"lens-sweep\" data-part=\"lens-sweep\" opacity=\"0\"><path class=\"k\" style=\"stroke:var(--pinch-spark,#AAF059)\" d=\"M129.48 50.25L151.98 72.75\" stroke-width=\"5\"/></g></g><circle class=\"u\" cx=\"140.73\" cy=\"61.5\" r=\"13.4\" style=\"stroke-width:calc(2.2 + 2*var(--pinch-ow,3))\"/><circle class=\"k sl\" cx=\"140.73\" cy=\"61.5\" r=\"12.5\" stroke-width=\"4\"/><g id=\"lens-glint\" data-part=\"lens-glint\"><path class=\"k\" style=\"stroke:var(--p-glint)\" d=\"M133.13 59.32A7.9 7.9 0 0 1 136.54 54.8\" stroke-width=\"2.4\" stroke-opacity=\".7\"/><path class=\"k\" style=\"stroke:var(--p-glint)\" d=\"M143.69 54.18A7.9 7.9 0 0 1 145.37 55.11\" stroke-width=\"2.4\" stroke-opacity=\".7\"/></g></g><g transform=\"translate(125.5 115) rotate(14) scale(-0.86 0.86)\"><g id=\"jaw-r-top\" data-part=\"jaw-r-top\"><path class=\"o fb\" d=\"M-12.6 -17.5A36.3 36.3 0 0 1 -7.64 -43.78A2.6 2.6 0 0 1 -2.7 -42.17A23.04 23.04 0 0 0 -3.2 -25.5L-1.5 -18Z\"/></g><circle class=\"o fb\" cx=\"0\" cy=\"-14\" r=\"13\"/><path class=\"fs lod-40\" d=\"M-12.4 -11A13 13 0 0 0 12.4 -11A19.5 19.5 0 0 1 -12.4 -11Z\"/></g></g></g><g id=\"sweat\" data-part=\"sweat\" opacity=\"0\"><path style=\"fill:var(--pinch-lens,#D7D7D7)\" d=\"M60.5 50C62.9 54 64.9 55.8 64.9 58.4A4.4 4.4 0 0 1 56.1 58.4C56.1 55.8 58.1 54 60.5 50Z\"/><path class=\"k\" style=\"stroke:var(--pinch-shine,#FFF)\" d=\"M58.3 58a2.4 2.4 0 0 0 1.8 2.2\" stroke-width=\"1.3\"/></g><g id=\"zzz\" data-part=\"zzz\" opacity=\"0\"><path data-part=\"z0\" class=\"k ss\" d=\"M112 36h5l-5 5h5\" stroke-width=\"1.6\"/><path data-part=\"z1\" class=\"k ss\" d=\"M121 25h6.5l-6.5 6.5h6.5\" stroke-width=\"1.95\"/><path data-part=\"z2\" class=\"k ss\" d=\"M131 12h8l-8 8h8\" stroke-width=\"2.3\"/></g></g><g id=\"sparkle\" data-part=\"sparkle\" opacity=\"0\"><path data-part=\"spark0\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M14 23Q15.4 28.6 21 30Q15.4 31.4 14 37Q12.6 31.4 7 30Q12.6 28.6 14 23Z\"/><path data-part=\"spark1\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M146 23Q147.4 28.6 153 30Q147.4 31.4 146 37Q144.6 31.4 139 30Q144.6 28.6 146 23Z\"/><path data-part=\"spark2\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M27 8.8Q27.84 12.16 31.2 13Q27.84 13.84 27 17.2Q26.16 13.84 22.8 13Q26.16 12.16 27 8.8Z\"/><path data-part=\"spark3\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M133 7.8Q133.84 11.16 137.2 12Q133.84 12.84 133 16.2Q132.16 12.84 128.8 12Q132.16 11.16 133 7.8Z\"/><path data-part=\"spark4\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M6 54.4Q6.72 57.28 9.6 58Q6.72 58.72 6 61.6Q5.28 58.72 2.4 58Q5.28 57.28 6 54.4Z\"/><path data-part=\"spark5\" style=\"fill:var(--pinch-spark,#AAF059)\" d=\"M154 54.4Q154.72 57.28 157.6 58Q154.72 58.72 154 61.6Q153.28 58.72 150.4 58Q153.28 57.28 154 54.4Z\"/></g></svg>\n","lod20":"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" width=\"20\" height=\"20\" class=\"pinch-glyph\" role=\"img\" aria-label=\"Pinch\"><style>.pinch-glyph .ps{fill:var(--pinch-silhouette,var(--pinch-body,#76B900))}.pinch-glyph .pl{fill:var(--pinch-lens,#D7D7D7)}.pinch-glyph .pe{fill:var(--pinch-eye,#000)}.pinch-glyph .pw{fill:var(--pinch-shine,#FFF)}.pinch-glyph .pg{fill:var(--pinch-spark,#AAF059)}.pinch-glyph.lit #lens-glow{opacity:1}</style><g id=\"pinch-root\"><path id=\"body\" class=\"ps\" d=\"M10.6 6.6C13.1 6.6 14.5 9.1 15.1 11.6L16 15.6C16.5 17.7 15.1 19.4 13.1 19.4H8.1C6.1 19.4 4.7 17.7 5.2 15.6L6.1 11.6C6.7 9.1 8.1 6.6 10.6 6.6Z\"/><path id=\"claw-l\" class=\"ps\" transform=\"translate(1.9 1.5) rotate(-16 3.5 10.3)\" d=\"M3.2 10.3C1.3 9.9 0.4 8.2 0.6 6.2L1.3 2C1.45 1.25 2.55 1.25 2.7 2L2.8 4.7C2.85 5.3 4.05 5.3 4.1 4.7L4.2 2C4.35 1.25 5.45 1.25 5.6 2L6.3 6.2C6.6 8.2 5.7 9.8 4.2 10.3Z\"/><g id=\"lens\"><path class=\"pl\" fill-rule=\"evenodd\" d=\"M16.3 1.6a3.4 3.4 0 1 1 0 6.8a3.4 3.4 0 1 1 0 -6.8ZM16.3 3.6a1.4 1.4 0 1 0 0 2.8a1.4 1.4 0 1 0 0 -2.8ZM13.7 7.6L15.1 8.6L13.3 11.7L11.9 10.8Z\"/><circle id=\"lens-glow\" class=\"pg\" cx=\"16.3\" cy=\"5\" r=\"1.45\" opacity=\"0\"/></g><path id=\"eye-l\" class=\"pe\" d=\"M7.35 12.1H9.85V13.95A1.25 1.25 0 0 1 7.35 13.95Z\"/><circle class=\"pw\" cx=\"8.15\" cy=\"12.85\" r=\"0.55\"/><path id=\"eye-r\" class=\"pe\" d=\"M11.35 12.1H13.85V13.95A1.25 1.25 0 0 1 11.35 13.95Z\"/><circle class=\"pw\" cx=\"12.15\" cy=\"12.85\" r=\"0.55\"/></g></svg>\n","lod16":"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 16 16\" width=\"16\" height=\"16\" class=\"pinch-glyph\" role=\"img\" aria-label=\"Pinch\"><style>.pinch-glyph .ps{fill:var(--pinch-silhouette,var(--pinch-body,#76B900))}.pinch-glyph .pl{fill:var(--pinch-lens,#D7D7D7)}.pinch-glyph .pe{fill:var(--pinch-eye,#000)}.pinch-glyph .pw{fill:var(--pinch-shine,#FFF)}.pinch-glyph .pg{fill:var(--pinch-spark,#AAF059)}.pinch-glyph.lit #lens-glow{opacity:1}</style><g id=\"pinch-root\"><path id=\"body\" class=\"ps\" d=\"M8.5 5.4C10.5 5.4 11.6 7.4 12.1 9.4L12.8 12.5C13.2 14.2 12.1 15.5 10.5 15.5H6.5C4.9 15.5 3.8 14.2 4.2 12.5L4.9 9.4C5.4 7.4 6.5 5.4 8.5 5.4Z\"/><path id=\"claw-l\" class=\"ps\" transform=\"translate(1.5 1.2) rotate(-16 2.8 8.3)\" d=\"M2.6 8.3C1.1 8 0.3 6.6 0.5 5L1.1 1.6C1.2 1 2.1 1 2.2 1.6L2.25 3.8C2.3 4.3 3.3 4.3 3.35 3.8L3.4 1.6C3.5 1 4.4 1 4.5 1.6L5.1 5C5.3 6.6 4.6 7.9 3.4 8.3Z\"/><g id=\"lens\"><path class=\"pl\" fill-rule=\"evenodd\" d=\"M13 1.4a2.7 2.7 0 1 1 0 5.4a2.7 2.7 0 1 1 0 -5.4ZM13 3a1.1 1.1 0 1 0 0 2.2a1.1 1.1 0 1 0 0 -2.2ZM10.9 6.2L12 7L10.6 9.4L9.5 8.7Z\"/><circle id=\"lens-glow\" class=\"pg\" cx=\"13\" cy=\"4.1\" r=\"1.15\" opacity=\"0\"/></g><path id=\"eye-l\" class=\"pe\" d=\"M5.9 9.7H7.9V11.2A1 1 0 0 1 5.9 11.2Z\"/><path id=\"eye-r\" class=\"pe\" d=\"M9.1 9.7H11.1V11.2A1 1 0 0 1 9.1 11.2Z\"/></g></svg>\n"};
  var RIG = {"viewBox":[0,0,160,160],"units":"viewBox user units; every transform is an SVG transform attribute about the listed pivot (equivalent to transform-box: view-box)","feet":[80,148],"order":"bloom, pinch-root > [tail, legs, body > [antenna-l, antenna-r, torso, belly, blush, eye-l > lid-l, eye-r > lid-r, mouth], arm-l > claw-l > [jaw-l-bottom, jaw-l-top, palm, paper], arm-r > claw-r > [jaw-r-bottom, lens > [lens-glow, lens-view > lens-eye, rim, lens-glint], jaw-r-top, palm], sweat, zzz], sparkle","parts":{"pinch-root":{"pivot":[80,148],"parent":null,"transforms":"translate(0,bodyY) rotate(tilt + 2*lookX, feet) scale(1/sqrt(bodySquash), bodySquash, feet)"},"bloom":{"pivot":[80,86],"parent":null,"transforms":"opacity bloom; scale 0.8+0.2*bloom"},"tail":{"pivot":[48,133],"parent":"pinch-root","transforms":"static (LOD: hidden below 40 px)"},"legs":{"pivot":[80,140],"parent":"pinch-root","transforms":"static (LOD: hidden below 96 px)"},"body":{"pivot":[80,144],"parent":"pinch-root","transforms":"static carrier for face parts"},"antenna-l":{"pivot":[74.5,38],"parent":"body","transforms":"rotate(antennaLift + antennaSway)"},"antenna-r":{"pivot":[85.5,38],"parent":"body","transforms":"rotate(-antennaLift + 0.85*antennaSway)"},"belly":{"pivot":[80,122.5],"parent":"body","transforms":"static"},"blush":{"pivot":[80,94.5],"parent":"body","transforms":"opacity blush"},"eye-l":{"pivot":[66,80],"parent":"body","transforms":"translate(lookX*3.5, lookY*2.5) scale(max(1,eyeOpen))"},"eye-r":{"pivot":[94,80],"parent":"body","transforms":"translate(lookX*3.5, lookY*2.5) scale(max(1,eyeOpen))"},"lid-l":{"pivot":[66,66],"parent":"eye-l","transforms":"translate(0, coverage*lidSpan) rotate(-browL, lid edge); clipped to the eye"},"lid-r":{"pivot":[94,66],"parent":"eye-r","transforms":"translate(0, coverage*lidSpan) rotate(browR, lid edge)"},"mouth":{"pivot":[80,97],"parent":"body","transforms":"rotate(mouthTilt); child shape by mouth; smile scaleY(mouthCurve) about its corners"},"arm-l":{"pivot":[51.5,104.5],"parent":"pinch-root","transforms":"rotate(clawL)"},"claw-l":{"pivot":[31.5,89],"parent":"arm-l","transforms":"rotate(-0.8*clawL + wristL)"},"jaw-l-top":{"pivot":[13.8,69.9],"parent":"claw-l","transforms":"rotate(jaw angle) about jaws.top.local (dactyl)"},"jaw-l-bottom":{"pivot":[29.2,63.1],"parent":"claw-l","transforms":"rotate(jaw angle) about jaws.bottom.local (fixed finger)"},"paper":{"pivot":[31.5,89],"parent":"claw-l","transforms":"opacity paper"},"arm-r":{"pivot":[108,105],"parent":"pinch-root","transforms":"rotate(-clawR + lens*lensRaise.arm)"},"claw-r":{"pivot":[125.5,115],"parent":"arm-r","transforms":"rotate(0.8*clawR - wristR + lens*lensRaise.claw)"},"jaw-r-top":{"pivot":[136.3,98.2],"parent":"claw-r","transforms":"as jaw-l-top (the claw frame is mirrored, same signed angle closes)"},"jaw-r-bottom":{"pivot":[123.8,95.1],"parent":"claw-r","transforms":"as jaw-l-bottom"},"lens":{"pivot":[130.49,94.97],"parent":"claw-r","transforms":"translate(lens*lensRaise.slide) scale(lensZoom, glass) scale(1-0.35*lensOut, grip); opacity 1-lensOut"},"lens-glow":{"pivot":[140.73,61.5],"parent":"lens","transforms":"children lens-ring, lens-wash: opacity lensGlow"},"lens-glint":{"pivot":[140.73,61.5],"parent":"lens","transforms":"static specular arcs at 10 and 2 o'clock"},"lens-sweep":{"pivot":[140.73,61.5],"parent":"lens","transforms":"translate along the 45 deg diagonal (-1.25..1.25)*r by glint; opacity sin(pi*glint); clipped to the glass"},"lens-view":{"pivot":[140.73,61.5],"parent":"lens","transforms":"opacity smoothstep(0.72,0.96,lens); clipped to the glass"},"lens-eye":{"pivot":[94,80],"parent":"lens-view","transforms":"matrix = inverse(world(lens)) * scale(1.5 about the glass centre in world) * world(eye-r)"},"sweat":{"pivot":[60.5,57],"parent":"pinch-root","transforms":"opacity sweat; translateY 3.5*(sweat-1)"},"zzz":{"pivot":[121,25],"parent":"pinch-root","transforms":"opacity zzz; z0..z2 drift (5,-11)*phase on a 2400 ms cycle"},"sparkle":{"pivot":[80,64],"parent":null,"transforms":"opacity 1.6*sparkle; scale 0.72+0.34*sparkle about the centre"}},"jaws":{"l":{"top":{"local":[-7.5,-22],"world":[13.8,69.9],"close_deg":13.5,"open_deg":-16},"bottom":{"local":[7.5,-22],"world":[29.2,63.1],"close_deg":-3,"open_deg":5}},"r":{"top":{"local":[-7.5,-22],"world":[136.3,98.2],"close_deg":13.5,"open_deg":-16},"bottom":{"local":[7.5,-22],"world":[123.8,95.1],"close_deg":-3,"open_deg":5}}},"params":[{"name":"bodySquash","default":1,"min":0.85,"max":1.15,"unit":"scaleY","drives":"pinch-root scale about the feet [80,148]; scaleX = 1/sqrt(scaleY)"},{"name":"bodyY","default":0,"min":-24,"max":8,"unit":"px","drives":"pinch-root translateY (hops: ease-out up, ease-in down)"},{"name":"tilt","default":0,"min":-12,"max":12,"unit":"deg","drives":"pinch-root rotate about the feet; lookX adds a 2 deg lean"},{"name":"clawL","default":0,"min":-40,"max":45,"unit":"deg","drives":"arm-l rotate about the shoulder (+ raises); claw-l counter-rotates -0.8x so it stays upright"},{"name":"clawR","default":0,"min":-40,"max":86,"unit":"deg","drives":"arm-r rotate about the shoulder (+ raises, mirrored sign); claw-r counter-rotates -0.8x"},{"name":"wristL","default":0,"min":-60,"max":140,"unit":"deg","drives":"extra claw-l rotate about the wrist (+ turns the crusher in toward the face: thinking, clap)"},{"name":"wristR","default":0,"min":-60,"max":140,"unit":"deg","drives":"extra claw-r rotate about the wrist, mirrored sense"},{"name":"pinch","default":0,"min":-1,"max":1,"unit":"0..1","drives":"both claws: -1 wide open, 0 rest gap, 1 jaws meet (close_deg)"},{"name":"pinchL","default":0,"min":-1,"max":1,"unit":"0..1","drives":"crusher only, added to pinch and clamped"},{"name":"pinchR","default":0,"min":-1,"max":1,"unit":"0..1","drives":"cutter only (grips the lens handle), added to pinch and clamped"},{"name":"eyeOpen","default":1,"min":0,"max":1.3,"unit":"0..1.3","drives":"both lids: coverage = 1 - eyeOpen; above 1 the eyes scale up (surprise 1.15)"},{"name":"lidL","default":0,"min":0,"max":1,"unit":"0..1","drives":"extra lid coverage on eye-l, combined 1-(1-a)(1-b) with eyeOpen (sideeye dry lid 0.4)"},{"name":"lidR","default":0,"min":0,"max":1,"unit":"0..1","drives":"extra lid coverage on eye-r"},{"name":"browL","default":0,"min":-8,"max":14,"unit":"deg","drives":"lid-l tilt: + kind (outer corner down), - dry; never a frown"},{"name":"browR","default":0,"min":-8,"max":14,"unit":"deg","drives":"lid-r tilt, same sense mirrored"},{"name":"joy","default":0,"min":0,"max":1,"unit":"0..1","drives":"crossfade the eyes to happy closed ^ ^ arcs (celebrate)"},{"name":"lookX","default":0,"min":-1,"max":1,"unit":"-1..1","drives":"eye-l/eye-r translateX +-3.5 (lids ride along), body lean 2 deg"},{"name":"lookY","default":0,"min":-1,"max":1,"unit":"-1..1","drives":"eye-l/eye-r translateY +-2.5"},{"name":"mouth","default":"smile","min":null,"max":null,"unit":"shape","drives":"the only shape swap: smile | flat | open | o (step)"},{"name":"mouthCurve","default":1,"min":-0.2,"max":1.4,"unit":"scaleY","drives":"smile height (0 = flat line, 1 = rest smile); clamped at -0.2, never a frown"},{"name":"mouthTilt","default":0,"min":-14,"max":14,"unit":"deg","drives":"mouth rotate about its centre (half smile)"},{"name":"blush","default":0,"min":0,"max":1,"unit":"0..1","drives":"blush opacity (pinch-blush already carries its alpha)"},{"name":"antennaSway","default":0,"min":-16,"max":16,"unit":"deg","drives":"both antennae rotate the same way (right one x0.85)"},{"name":"antennaLift","default":0,"min":-16,"max":24,"unit":"deg","drives":"antennae perk up (+) or droop (-), mirrored"},{"name":"sparkle","default":0,"min":0,"max":1,"unit":"0..1","drives":"sparkle opacity and burst scale 0.72 -> 1.06"},{"name":"sweat","default":0,"min":0,"max":1,"unit":"0..1","drives":"sweat drop opacity, slides 3.5 px down as it appears"},{"name":"zzz","default":0,"min":0,"max":1,"unit":"0..1","drives":"z opacity; the three z's drift on a 2400 ms cycle of engine time"},{"name":"lens","default":0,"min":0,"max":1,"unit":"0..1","drives":"0 lowered in the cutter -> 1 glass on eye-r (IK macro on arm-r, claw-r, lens); lens-view shows the magnified eye from 0.72"},{"name":"lensGlow","default":0,"min":0,"max":1,"unit":"0..1","drives":"camera light: green wash in the glass + a ring outside the rim. Carries information: never animate it for decoration"},{"name":"lensZoom","default":1,"min":0.8,"max":1.4,"unit":"scale","drives":"lens scale about the glass centre (the tap toward the viewer)"},{"name":"lensOut","default":0,"min":0,"max":1,"unit":"0..1","drives":"lens tucked away (opacity 0, scale 0.65 about the grip) so both claws can clap"},{"name":"glint","default":0,"min":0,"max":1,"unit":"0..1","drives":"one green glint sweeps across the glass, opacity sin(pi*glint) (connected)"},{"name":"paper","default":0,"min":0,"max":1,"unit":"0..1","drives":"paper slip in the crusher (reading)"},{"name":"bloom","default":0,"min":0,"max":1,"unit":"0..1","drives":"the one allowed gradient, behind Pinch, celebrate only"}],"geom":{"eyes":{"l":[66,80],"r":[94,80]},"eyeR":[9.4,11.2],"look":[3.5,2.5],"lookLean":2,"lidSpan":26.4,"lidEdge":{"l":66,"r":66},"mouth":[80,97],"smileY":95.4,"antenna":{"l":[74.5,38],"r":[85.5,38]},"shoulder":{"l":[51.5,104.5],"r":[108,105]},"wrist":{"l":[31.5,89],"r":[125.5,115]},"clawFollow":-0.8,"clawFrame":{"l":"translate(31.5 89) rotate(-24) scale(1.12 1.12)","r":"translate(125.5 115) rotate(14) scale(-0.86 0.86)"},"jaws":{"top":{"local":[-7.5,-22],"close_deg":13.5,"open_deg":-16},"bottom":{"local":[7.5,-22],"close_deg":-3,"open_deg":5}},"glass":[140.73,61.5],"glassR":12.5,"grip":[130.49,94.97],"lensMag":1.5,"lensRaise":{"arm":18.29,"claw":-67.85,"slide":[-2.047,6.694],"target":[94.4,79.6]},"sweat":[60.5,57],"sparkleC":[80,64],"bloom":[80,86],"zzzPeriod":2400}};
  var CLIPS = {"moods":{"idle":{"loop":true,"dur":4000,"key":0,"tracks":{"bodySquash":[[0,1],[2000,1.025,"sine"],[4000,1,"sine"]],"antennaSway":[[0,0],[1000,3.5,"sine"],[3000,-3.5,"sine"],[4000,0,"sine"]],"antennaLift":[[0,0],[2070,1.5,"sine"],[4000,0,"sine"]]}},"focused":{"loop":true,"dur":3000,"key":0,"tracks":{"eyeOpen":[[0,0.8]],"browL":[[0,4]],"browR":[[0,4]],"lensGlow":[[0,1]],"lookY":[[0,0.2]],"lookX":[[0,-0.12],[1500,0.12,"sine"],[3000,-0.12,"sine"]],"tilt":[[0,-2.5]],"bodySquash":[[0,1],[1500,1.015,"sine"],[3000,1,"sine"]],"antennaLift":[[0,3]],"antennaSway":[[0,0],[70,0],[190,2.5,"out"],[520,0,"settle"],[1570,0],[1690,-2.5,"out"],[2020,0,"settle"]],"clawL":[[0,0],[120,7,"out"],[420,0,"settle"]],"clawR":[[0,0],[1500,0],[1620,7,"out"],[1920,0,"settle"]],"mouthCurve":[[0,0.85]]}},"listening":{"loop":true,"dur":4000,"key":0,"tracks":{"eyeOpen":[[0,1.1]],"lookY":[[0,0.55]],"tilt":[[0,4]],"antennaLift":[[0,8],[2070,9.5,"sine"],[4000,8,"sine"]],"antennaSway":[[0,2]],"clawL":[[0,6]],"bodySquash":[[0,1],[2000,1.02,"sine"],[4000,1,"sine"]],"mouthCurve":[[0,0.85]]}},"thinking":{"loop":true,"dur":1200,"key":150,"tracks":{"lens":[[0,0.5],[150,0.58,"out"],[330,0.5,"settle"],[600,0.5],[750,0.58,"out"],[930,0.5,"settle"]],"lookX":[[0,-0.75]],"lookY":[[0,-0.85]],"antennaSway":[[0,-6],[300,6,"sine"],[600,-6,"sine"],[900,6,"sine"],[1200,-6,"sine"]],"antennaLift":[[0,4]],"mouth":[[0,"flat"]],"mouthTilt":[[0,-7]],"eyeOpen":[[0,0.95]],"tilt":[[0,-3]],"clawL":[[0,-8]]}},"sleepy":{"loop":true,"dur":5000,"key":1250,"tracks":{"eyeOpen":[[0,0.3]],"bodySquash":[[0,0.97],[2500,0.985,"sine"],[5000,0.97,"sine"]],"bodyY":[[0,0],[2500,1.2,"sine"],[5000,0,"sine"]],"tilt":[[0,-2.5],[2500,2.5,"sine"],[5000,-2.5,"sine"]],"antennaLift":[[0,-12],[2570,-9,"sine"],[5000,-12,"sine"]],"antennaSway":[[0,-3],[2570,3,"sine"],[5000,-3,"sine"]],"lookY":[[0,0.4]],"zzz":[[0,1]],"mouthCurve":[[0,0.35]],"clawL":[[0,-14]],"clawR":[[0,-8]],"lensGlow":[[0,0]]}},"reading":{"loop":true,"dur":2400,"key":300,"tracks":{"paper":[[0,1]],"lens":[[0,1]],"lookX":[[0,-0.75],[1100,-0.15,"in-out"],[1250,-0.15],[1450,-0.75,"out"],[2400,-0.75]],"lookY":[[0,0.1],[1100,0.25,"in-out"],[1450,0.4,"out"],[2400,0.1,"in-out"]],"bodySquash":[[0,1],[1200,1.015,"sine"],[2400,1,"sine"]],"antennaLift":[[0,4]],"antennaSway":[[0,-2],[1170,2,"in-out"],[1520,-2,"out"]],"mouthCurve":[[0,0.6]],"tilt":[[0,-2]]}}},"clips":{"hello":{"loop":false,"dur":1400,"priority":1,"key":420,"tracks":{"bodySquash":[[0,1],[150,0.9,"anticip"],[330,1.08,"overshoot"],[480,0.98,"out"],[800,1,"settle"]],"bodyY":[[0,0],[150,2,"anticip"],[330,-8,"out"],[520,0,"anticip"]],"antennaLift":[[0,0],[220,-8,"anticip"],[400,14,"overshoot"],[560,-4,"out"],[900,0,"settle"]],"clawL":[[0,0],[150,-8,"anticip"],[370,32,"overshoot"],[540,14,"in-out"],[710,32,"in-out"],[880,14,"in-out"],[1050,26,"in-out"],[1400,0,"settle"]],"wristL":[[0,0],[370,-10,"out"],[540,12,"in-out"],[710,-10,"in-out"],[880,12,"in-out"],[1050,-6,"in-out"],[1400,0,"settle"]],"mouth":[[0,"smile"],[300,"open"],[1000,"smile"]],"eyeOpen":[[0,1],[150,0.85,"anticip"],[330,1.12,"overshoot"],[700,1,"out"]],"blush":[[0,0],[400,0.6,"out"],[1100,0.6],[1400,0,"out"]],"tilt":[[0,0],[330,-3,"out"],[700,3,"sine"],[1050,-2,"sine"],[1400,0,"settle"]],"pinchL":[[960,0],[1050,1,"out"],[1190,0,"out"],[1280,1,"out"],[1370,0,"out"]]}},"sideeye":{"loop":false,"dur":1400,"priority":4,"key":720,"tracks":{"bodySquash":[[0,1],[140,0.97,"anticip"],[380,1.01,"out"],[1400,1]],"clawR":[[0,0],[140,-8,"anticip"],[380,0,"out"]],"lens":[[0,0],[140,0],[420,1,"overshoot"],[1100,1],[1400,0,"in-out"]],"tilt":[[0,0],[140,1.5,"anticip"],[420,-5,"out"],[1100,-5],[1400,0,"settle"]],"lookX":[[0,0],[160,0],[380,0.75,"out"],[700,0.75],[820,0.9,"out"],[1100,0.9],[1400,0,"in-out"]],"lookY":[[0,0],[380,0.3,"out"],[1100,0.3],[1400,0,"in-out"]],"lidL":[[0,0],[200,0],[420,0.42,"out"],[1100,0.42],[1360,0,"in-out"]],"browL":[[0,0],[420,-5,"out"],[1100,-5],[1360,0,"in-out"]],"antennaLift":[[0,0],[230,-2,"anticip"],[490,5,"overshoot"],[1170,5],[1400,0,"settle"]],"antennaSway":[[0,0],[230,3,"anticip"],[490,-9,"overshoot"],[700,-6,"out"],[1170,-6],[1400,0,"settle"]],"mouth":[[0,"smile"],[380,"flat"],[1250,"smile"]],"mouthTilt":[[0,0],[380,-8,"out"],[1250,0,"out"]],"lensGlow":[[0,0],[420,1,"out"],[1100,1],[1400,0,"out"]]}},"nudge":{"loop":false,"dur":900,"priority":4,"key":330,"tracks":{"clawR":[[0,0],[150,-12,"anticip"],[300,14,"overshoot"],[560,6,"out"],[900,0,"settle"]],"lens":[[0,0],[150,0,"anticip"],[300,0.22,"out"],[560,0.18],[900,0,"settle"]],"lensZoom":[[0,1],[150,0.92,"anticip"],[300,1.3,"overshoot"],[460,1.16,"out"],[900,1,"settle"]],"pinchL":[[0,0],[360,0],[420,1,"out"],[540,0,"out"],[600,1,"out"],[720,0,"out"]],"clawL":[[0,0],[150,-6,"anticip"],[340,12,"overshoot"],[700,8],[900,0,"settle"]],"sweat":[[0,0],[200,1,"out"],[700,1],[900,0,"out"]],"eyeOpen":[[0,1],[150,0.9,"anticip"],[300,1.06,"out"],[900,1,"out"]],"mouth":[[0,"smile"],[120,"flat"],[300,"smile"]],"mouthCurve":[[0,1],[300,0.55,"out"],[900,1,"out"]],"bodySquash":[[0,1],[150,0.95,"anticip"],[300,1.04,"overshoot"],[500,1,"settle"]],"tilt":[[0,0],[150,-3,"anticip"],[300,3,"out"],[900,0,"settle"]],"antennaSway":[[0,0],[220,-6,"anticip"],[370,8,"overshoot"],[600,-2,"out"],[900,0,"settle"]],"lensGlow":[[0,0],[300,1,"out"],[700,1],[900,0,"out"]]}},"celebrate":{"loop":false,"dur":1600,"priority":5,"key":760,"tracks":{"lensOut":[[0,0],[120,1,"out"],[1250,1],[1600,0,"out"]],"bodySquash":[[0,1],[160,0.88,"anticip"],[380,1.12,"overshoot"],[520,0.9,"out"],[640,1.04,"out"],[800,1,"settle"]],"bodyY":[[0,0],[160,4,"anticip"],[380,-18,"out"],[520,0,"anticip"]],"clawL":[[0,0],[160,-10,"anticip"],[420,34,"overshoot"],[560,26,"out"],[1250,26],[1600,0,"settle"]],"clawR":[[0,0],[160,-10,"anticip"],[420,84,"overshoot"],[560,74,"out"],[1250,74],[1600,0,"settle"]],"wristL":[[0,0],[420,6,"out"],[1250,6],[1600,0,"settle"]],"wristR":[[0,0],[420,10,"out"],[1250,10],[1600,0,"settle"]],"pinch":[[0,0],[600,0],[690,1,"out"],[830,0,"out"],[920,1,"out"],[1060,0,"out"]],"joy":[[0,0],[200,1,"out"],[1300,1],[1560,0,"out"]],"mouth":[[0,"smile"],[200,"open"],[1350,"smile"]],"blush":[[0,0],[380,0.6,"out"],[520,0.85,"out"],[1200,0.85],[1600,0,"out"]],"sparkle":[[0,0],[380,0],[560,1,"out"],[900,0.8],[1300,0.2,"out"],[1600,0]],"bloom":[[0,0],[350,1,"out"],[1100,0.8],[1600,0,"in-out"]],"antennaLift":[[0,0],[230,6,"anticip"],[450,-14,"out"],[590,14,"overshoot"],[710,-4,"out"],[870,2,"out"],[1100,0,"settle"]],"tilt":[[0,0],[800,0],[960,-3,"sine"],[1120,3,"sine"],[1300,0,"settle"]]}},"partial":{"loop":false,"dur":1000,"priority":5,"key":380,"tracks":{"clawL":[[0,0],[140,-6,"anticip"],[380,30,"overshoot"],[760,28],[1000,0,"settle"]],"wristL":[[0,0],[380,-14,"out"],[760,-14],[1000,0,"settle"]],"clawR":[[0,0],[180,-12,"out"],[700,-12],[1000,0,"settle"]],"bodySquash":[[0,1],[140,0.97,"anticip"],[300,1.02,"out"],[420,0.975,"in-out"],[560,1.01,"in-out"],[680,0.98,"in-out"],[900,1,"settle"]],"lookY":[[0,0],[300,0.45,"in-out"],[420,0,"in-out"],[560,0.45,"in-out"],[680,0,"in-out"]],"mouthCurve":[[0,1],[300,0.6,"out"],[800,0.6],[1000,1,"out"]],"mouthTilt":[[0,0],[300,-11,"out"],[800,-11],[1000,0,"out"]],"tilt":[[0,0],[140,-1.5,"anticip"],[340,4,"out"],[760,3],[1000,0,"settle"]],"browL":[[0,0],[300,5,"out"],[800,5],[1000,0]],"browR":[[0,0],[300,5,"out"],[800,5],[1000,0]],"antennaSway":[[0,0],[210,-3,"anticip"],[410,6,"overshoot"],[830,4],[1000,0,"settle"]]}},"supportive":{"loop":false,"dur":1400,"priority":5,"key":460,"tracks":{"browL":[[0,0],[300,9,"out"],[1100,9],[1400,0,"in-out"]],"browR":[[0,0],[300,9,"out"],[1100,9],[1400,0,"in-out"]],"lidL":[[0,0],[300,0.2,"out"],[1100,0.2],[1400,0,"in-out"]],"lidR":[[0,0],[300,0.2,"out"],[1100,0.2],[1400,0,"in-out"]],"eyeOpen":[[0,1],[520,1],[700,0.08,"in-out"],[900,1,"in-out"]],"clawL":[[0,0],[200,-20,"out"],[1150,-20],[1400,0,"settle"]],"clawR":[[0,0],[240,-16,"out"],[1190,-16],[1400,0,"settle"]],"tilt":[[0,0],[300,5,"in-out"],[1100,5],[1400,0,"settle"]],"lookY":[[0,0],[420,0],[680,0.6,"in-out"],[940,0,"in-out"]],"bodySquash":[[0,1],[420,1],[680,0.97,"in-out"],[940,1,"in-out"]],"mouthCurve":[[0,1],[300,1.2,"out"],[1100,1.2],[1400,1,"out"]],"antennaLift":[[0,0],[370,-5,"out"],[1170,-5],[1400,0,"settle"]],"blush":[[0,0],[300,0.5,"out"],[1100,0.5],[1400,0]]}},"surprise":{"loop":false,"dur":700,"priority":3,"key":260,"tracks":{"eyeOpen":[[0,1],[80,0.85,"anticip"],[200,1.15,"overshoot"],[480,1.1],[700,1,"out"]],"bodySquash":[[0,1],[80,0.95,"anticip"],[200,1.08,"overshoot"],[340,0.98,"out"],[600,1,"settle"]],"bodyY":[[0,0],[200,-3,"out"],[340,0,"anticip"]],"antennaLift":[[0,0],[150,-4,"anticip"],[280,22,"overshoot"],[400,10,"out"],[520,16,"out"],[700,0,"settle"]],"mouth":[[0,"smile"],[150,"o"],[450,"smile"]],"sweat":[[0,0],[200,0.9,"out"],[500,0.9],[700,0,"out"]],"lookY":[[0,0],[480,0],[580,0.5,"in-out"],[700,0,"in-out"]],"clawL":[[0,0],[80,-4,"anticip"],[240,10,"overshoot"],[700,0,"settle"]],"clawR":[[0,0],[80,-4,"anticip"],[240,8,"overshoot"],[700,0,"settle"]]}},"connected":{"loop":false,"dur":1000,"priority":2,"key":420,"tracks":{"lensGlow":[[0,0],[200,1,"out"],[520,1],[800,0,"in-out"]],"glint":[[0,0],[200,0],[620,1,"in-out"],[621,0,"step"]],"lensZoom":[[0,1],[120,0.94,"anticip"],[260,1.14,"overshoot"],[520,1,"settle"]],"clawR":[[0,0],[120,-6,"anticip"],[260,22,"overshoot"],[580,18],[1000,0,"settle"]],"sparkle":[[0,0],[200,0.6,"out"],[600,0.3],[900,0]],"eyeOpen":[[0,1],[260,1.06,"out"],[600,1,"out"]],"mouthCurve":[[0,1],[260,1.25,"out"],[800,1,"out"]],"blush":[[0,0],[260,0.4,"out"],[800,0,"out"]],"bodySquash":[[0,1],[120,0.97,"anticip"],[260,1.03,"overshoot"],[520,1,"settle"]],"antennaLift":[[0,0],[190,-3,"anticip"],[330,9,"overshoot"],[600,0,"settle"]],"pinchL":[[560,0],[650,1,"out"],[790,0,"out"],[880,1,"out"],[970,0,"out"]]}}},"blink":{"dur":140,"tracks":{"eyeOpen":[[0,1],[60,0.05,"anticip"],[140,1,"out"]]},"every_ms":[3000,6000],"double_chance":0.15,"double_gap_ms":180,"compose":"multiply eyeOpen; skipped while a clip drives eyeOpen or joy, and in still/reduced motion"},"easings":{"linear":"linear","step":"step","out":"cubic-bezier(0.23,1,0.32,1)","in-out":"cubic-bezier(0.65,0,0.35,1)","sine":"cubic-bezier(0.37,0,0.63,1)","anticip":"cubic-bezier(0.5,0,0.75,0)","overshoot":"cubic-bezier(0.2,0.9,0.3,1.25)","settle":"spring(350,0.4)","snappy":"spring(350,0.15)","smooth":"spring(500,0)","celebrate":"spring(600,0.4)"},"policy":{"cooldown_ms":90000,"priority_order":["celebrate","partial","supportive","sideeye","nudge","surprise","connected","hello"],"preempt":"a higher priority clip pre-empts a lower one even inside the cooldown; equal or lower is dropped, not queued","force":"{force:true} bypasses the cooldown (verdict clips, and the nudge chained after sideeye)","chain":{"sideeye":"nudge"},"max_sideeye_per_session":3,"blend_in_ms":120,"blend_out_ms":240,"idle_gaze":{"every_ms":[4000,8000],"lookX":[-0.35,0.35],"lookY":[-0.2,0.25],"dur_ms":420,"ease":"in-out","moods":["idle"]},"rest_after_ms":120000,"still":"still:true and prefers-reduced-motion: render seek(name, key) with no loop, no breath and no blink; clips crossfade 200 ms to their key frame; lensGlow still follows the camera state","composition":{"order":"neutral <- mood (loop time) <- clip (absolute, weighted by the blend) ; blink multiplies eyeOpen ; lookAt adds to lookX/lookY (clamped -1..1)","lensGlow":"max(host camera state, clip value): the lens never claims the camera is off while it samples","mouth":"string tracks switch at their key; the blend snaps the shape at 50%"}}};
  var LIB = {};
  (function (root) {
    'use strict';

    /* ---------- easing ---------- */
    var BEZ = {};
    function bezier(x1, y1, x2, y2) {
      function a(p1, p2) { return 1 - 3 * p2 + 3 * p1; }
      function b(p1, p2) { return 3 * p2 - 6 * p1; }
      function c(p1) { return 3 * p1; }
      function calc(t, p1, p2) { return ((a(p1, p2) * t + b(p1, p2)) * t + c(p1)) * t; }
      function slope(t, p1, p2) { return 3 * a(p1, p2) * t * t + 2 * b(p1, p2) * t + c(p1); }
      return function (x) {
        if (x <= 0) return 0;
        if (x >= 1) return 1;
        var t = x;
        for (var i = 0; i < 8; i++) {
          var s = slope(t, x1, x2);
          if (Math.abs(s) < 1e-6) break;
          t -= (calc(t, x1, x2) - x) / s;
        }
        if (t < 0 || t > 1) { // bisection fallback
          var lo = 0, hi = 1; t = x;
          for (var j = 0; j < 30; j++) { var v = calc(t, x1, x2); if (v < x) lo = t; else hi = t; t = (lo + hi) / 2; }
        }
        return calc(t, y1, y2);
      };
    }
    /* SwiftUI-compatible spring(duration, bounce): omega = 2pi/duration, damping ratio = 1 - bounce.
       Evaluated on real elapsed time so a long segment simply holds the settled value. */
    function spring(durMs, bounce, elapsedMs) {
      var t = Math.max(0, elapsedMs) / 1000, w = 2 * Math.PI / (durMs / 1000), z = 1 - bounce;
      if (z >= 1) return 1 - Math.exp(-w * t) * (1 + w * t);
      var wd = w * Math.sqrt(1 - z * z);
      return 1 - Math.exp(-z * w * t) * (Math.cos(wd * t) + (z * w / wd) * Math.sin(wd * t));
    }
    var EASINGS = null;
    function setEasings(map) { EASINGS = map || {}; }
    function ease(name, t, segMs, elapsedMs) {
      var spec = (EASINGS && EASINGS[name]) || name || 'linear';
      if (spec === 'linear') return t;
      if (spec === 'step') return t >= 1 ? 1 : 0;
      var m = /^cubic-bezier\(([^)]+)\)$/.exec(spec);
      if (m) {
        if (!BEZ[spec]) { var v = m[1].split(',').map(Number); BEZ[spec] = bezier(v[0], v[1], v[2], v[3]); }
        return BEZ[spec](t);
      }
      m = /^spring\(([^,]+),([^)]+)\)$/.exec(spec);
      if (m) return t >= 1 ? 1 : spring(Number(m[1]), Number(m[2]), elapsedMs == null ? t * segMs : elapsedMs);
      return t;
    }

    /* ---------- tracks ---------- */
    function sampleTrack(tr, ms) {
      if (!tr.length) return undefined;
      if (ms <= tr[0][0]) return tr[0][1];
      for (var i = 1; i < tr.length; i++) {
        var a = tr[i - 1], b = tr[i];
        if (ms < b[0]) {
          if (typeof b[1] !== 'number' || typeof a[1] !== 'number') return a[1];
          var seg = b[0] - a[0] || 1, k = (ms - a[0]) / seg;
          return a[1] + (b[1] - a[1]) * ease(b[2] || 'out', k, seg, ms - a[0]);
        }
      }
      return tr[tr.length - 1][1];
    }
    function sample(def, ms) {
      var out = {}, t = def.loop ? ((ms % def.dur) + def.dur) % def.dur : ms;
      for (var k in def.tracks) out[k] = sampleTrack(def.tracks[k], t);
      return out;
    }
    function neutral(rig) {
      var p = {};
      rig.params.forEach(function (d) { p[d.name] = d['default']; });
      return p;
    }
    function pose(rig, clips, name, ms) {
      setEasings(clips.easings);
      var p = neutral(rig), def = clips.moods[name] || clips.clips[name];
      var s = sample(def, ms == null ? (def.key || 0) : ms);
      for (var k in s) p[k] = s[k];
      return p;
    }

    /* ---------- tiny affine helpers: [a b c d e f] like SVG matrix() ---------- */
    function mul(m, n) {
      return [m[0] * n[0] + m[2] * n[1], m[1] * n[0] + m[3] * n[1], m[0] * n[2] + m[2] * n[3], m[1] * n[2] + m[3] * n[3],
        m[0] * n[4] + m[2] * n[5] + m[4], m[1] * n[4] + m[3] * n[5] + m[5]];
    }
    function T(x, y) { return [1, 0, 0, 1, x, y]; }
    function R(deg, cx, cy) {
      var r = deg * Math.PI / 180, c = Math.cos(r), s = Math.sin(r);
      return mul(mul(T(cx || 0, cy || 0), [c, s, -s, c, 0, 0]), T(-(cx || 0), -(cy || 0)));
    }
    function S(sx, sy, cx, cy) { return mul(mul(T(cx, cy), [sx, 0, 0, sy, 0, 0]), T(-cx, -cy)); }
    function inv(m) {
      var det = m[0] * m[3] - m[1] * m[2];
      return [m[3] / det, -m[1] / det, -m[2] / det, m[0] / det, (m[2] * m[5] - m[3] * m[4]) / det, (m[1] * m[4] - m[0] * m[5]) / det];
    }
    function ap(m, p) { return [m[0] * p[0] + m[2] * p[1] + m[4], m[1] * p[0] + m[3] * p[1] + m[5]]; }
    function str(m) { return 'matrix(' + m.map(function (v) { return +v.toFixed(4); }).join(' ') + ')'; }
    function n2(v) { return +(+v).toFixed(3); }
    function clamp(v, a, b) { return Math.max(a, Math.min(b, v)); }
    function smooth(a, b, v) { var t = clamp((v - a) / (b - a), 0, 1); return t * t * (3 - 2 * t); }

    /* ---------- apply ---------- */
    function apply(svg, p, rig, tMs) {
      var G = rig.geom, part = {};
      svg.querySelectorAll('[data-part]').forEach(function (el) { part[el.getAttribute('data-part')] = el; });
      function set(id, attr, v) { var el = part[id]; if (el) el.setAttribute(attr, v); }
      function op(id, v) { set(id, 'opacity', n2(clamp(v, 0, 1))); }

      // root: squash about the feet with volume kept, then tilt (+ gaze lean), then bodyY
      var sy = p.bodySquash, sx = 1 / Math.sqrt(sy), F = rig.feet;
      var rootM = mul(mul(T(0, p.bodyY), R(p.tilt + G.lookLean * p.lookX, F[0], F[1])), S(sx, sy, F[0], F[1]));
      set('pinch-root', 'transform', str(rootM));

      // antennae: lift is mirrored (both perk up), sway is same-direction (the right one at 0.85)
      set('antenna-l', 'transform', 'rotate(' + n2(p.antennaLift + p.antennaSway) + ' ' + G.antenna.l.join(' ') + ')');
      set('antenna-r', 'transform', 'rotate(' + n2(-p.antennaLift + 0.85 * p.antennaSway) + ' ' + G.antenna.r.join(' ') + ')');

      // eyes: gaze translate, >1 eyeOpen scales the eye up (surprise), joy crossfades to ^ ^
      var cEye = clamp(1 - p.eyeOpen, 0, 1), es = Math.max(1, p.eyeOpen);
      var eyeM = {};
      ['l', 'r'].forEach(function (s) {
        var c = G.eyes[s];
        var m = mul(T(p.lookX * G.look[0], p.lookY * G.look[1]), S(es, es, c[0], c[1]));
        eyeM[s] = m;
        set('eye-' + s, 'transform', str(m));
        var lid = s === 'l' ? p.lidL : p.lidR, brow = s === 'l' ? -p.browL : p.browR;
        var cov = clamp(1 - (1 - cEye) * (1 - lid), 0, 1);
        var lidT = 'translate(0 ' + n2(cov * G.lidSpan) + ') rotate(' + n2(brow) + ' ' + c[0] + ' ' + G.lidEdge[s] + ')';
        set('lid-' + s, 'transform', lidT);
        op('lid-' + s + '-lash', cov / 0.06);
        op('eye-' + s + '-open', 1 - p.joy);
        op('eye-' + s + '-joy', p.joy);
        if (s === 'r') { set('lens-lid', 'transform', lidT); op('lens-lid-lash', cov / 0.06); op('lens-eye-r-open', 1 - p.joy); }
      });

      // mouth: one of four shapes; smile height scales with mouthCurve (never below -0.2: no frowns)
      var shapes = ['smile', 'flat', 'open', 'o'];
      shapes.forEach(function (k) { op('mouth-' + k, p.mouth === k ? 1 : 0); });
      var mc = clamp(p.mouthCurve, -0.2, 1.4);
      set('mouth-smile', 'transform', 'translate(0 ' + n2(G.smileY * (1 - mc)) + ') scale(1 ' + n2(mc) + ')');
      set('mouth', 'transform', 'rotate(' + n2(p.mouthTilt) + ' ' + G.mouth.join(' ') + ')');
      op('blush', p.blush);

      // arms and claws: + is a raise on both sides. The lens macro adds its IK angles to the right side.
      var L = clamp(p.lens, 0, 1), LR = G.lensRaise;
      var armL = p.clawL, armR = -p.clawR + L * LR.arm;
      var clawL = G.clawFollow * p.clawL + p.wristL, clawR = -G.clawFollow * p.clawR - p.wristR + L * LR.claw;
      set('arm-l', 'transform', 'rotate(' + n2(armL) + ' ' + G.shoulder.l.join(' ') + ')');
      set('arm-r', 'transform', 'rotate(' + n2(armR) + ' ' + G.shoulder.r.join(' ') + ')');
      set('claw-l', 'transform', 'rotate(' + n2(clawL) + ' ' + G.wrist.l.join(' ') + ')');
      set('claw-r', 'transform', 'rotate(' + n2(clawR) + ' ' + G.wrist.r.join(' ') + ')');
      ['l', 'r'].forEach(function (s) {
        var v = clamp(p.pinch + (s === 'l' ? p.pinchL : p.pinchR), -1, 1), J = G.jaws;
        var top = v >= 0 ? v * J.top.close_deg : -v * J.top.open_deg;
        var bot = v >= 0 ? v * J.bottom.close_deg : -v * J.bottom.open_deg;
        set('jaw-' + s + '-top', 'transform', 'rotate(' + n2(top) + ' ' + J.top.local.join(' ') + ')');
        set('jaw-' + s + '-bottom', 'transform', 'rotate(' + n2(bot) + ' ' + J.bottom.local.join(' ') + ')');
      });

      // lens: slide along the handle, zoom about the glass, tuck away (celebrate) about the grip
      var gc = G.glass, grip = G.grip, out = clamp(p.lensOut, 0, 1);
      var lensM = mul(mul(T(L * LR.slide[0], L * LR.slide[1]), S(p.lensZoom, p.lensZoom, gc[0], gc[1])),
        S(1 - 0.35 * out, 1 - 0.35 * out, grip[0], grip[1]));
      set('lens', 'transform', str(lensM));
      op('lens', 1 - out);
      op('lens-ring', p.lensGlow);
      op('lens-wash', p.lensGlow);
      var gl = clamp(p.glint, 0, 1), sw = (2 * gl - 1) * 1.25 * G.glassR * 0.7071;
      set('lens-sweep', 'transform', 'translate(' + n2(-sw) + ' ' + n2(sw) + ')');
      op('lens-sweep', Math.sin(Math.PI * gl));
      // the magnified eye behind the glass: what is behind the lens, scaled about the glass centre
      var view = smooth(0.72, 0.96, L);
      op('lens-view', view);
      if (view > 0) {
        var W = mul(mul(R(armR, G.shoulder.r[0], G.shoulder.r[1]), R(clawR, G.wrist.r[0], G.wrist.r[1])), lensM);
        var gw = ap(W, gc);
        set('lens-eye', 'transform', str(mul(mul(inv(W), S(G.lensMag, G.lensMag, gw[0], gw[1])), eyeM.r)));
      }
      op('paper', p.paper);

      // effects
      op('sweat', p.sweat);
      set('sweat', 'transform', 'translate(0 ' + n2(3.5 * (clamp(p.sweat, 0, 1) - 1)) + ')');
      var spk = clamp(p.sparkle, 0, 1), sc = G.sparkleC;
      op('sparkle', spk * 1.6);
      set('sparkle', 'transform', str(S(0.72 + 0.34 * spk, 0.72 + 0.34 * spk, sc[0], sc[1])));
      op('bloom', p.bloom);
      set('bloom', 'transform', str(S(0.8 + 0.2 * p.bloom, 0.8 + 0.2 * p.bloom, G.bloom[0], G.bloom[1])));
      op('zzz', p.zzz);
      var ph = ((tMs || 0) % G.zzzPeriod) / G.zzzPeriod;
      for (var i = 0; i < 3; i++) {
        var q = (ph + i / 3) % 1;
        set('z' + i, 'transform', 'translate(' + n2(5 * q) + ' ' + n2(-11 * q) + ')');
        op('z' + i, Math.sin(Math.PI * q));
      }
    }

    function prefixIds(markup, prefix) {
      return markup
        .replace(/\bid="([^"]+)"/g, 'id="' + prefix + '$1"')
        .replace(/url\(#([^)]+)\)/g, 'url(#' + prefix + '$1)')
        .replace(/href="#([^"]+)"/g, 'href="#' + prefix + '$1"');
    }

    root.AlibiPinchRig = { neutral: neutral, sample: sample, sampleTrack: sampleTrack, pose: pose, apply: apply,
      prefixIds: prefixIds, ease: ease, setEasings: setEasings };
  })(LIB);
  /* @pinch-data:end */

  var R = LIB.AlibiPinchRig, POL = CLIPS.policy, MOODS = CLIPS.moods, SHOTS = CLIPS.clips, BLINK = CLIPS.blink;
  var GAZE = POL.idle_gaze, COOLDOWN = POL.cooldown_ms, REST = POL.rest_after_ms;
  var MOOD_MS = 420, WAKE_MS = 260, REST_MS = 600, FADE_MS = 200;
  // Ambient fidgets (the island's Pinch.swift plays the same tracks). Absolute values on their
  // params, blended in over 120 ms and out over 240 ms, under any clip. They never drive lensGlow: the lens glows only
  // while the camera samples.
  var FIDGETS = {
    inspect: { dur: 1600, tracks: {
      lens: [[0, 0], [420, 0.92, 'out'], [1150, 0.92], [1600, 0, 'in-out']],
      glint: [[0, 0], [520, 0], [980, 1, 'in-out'], [981, 0, 'step']],
      lookX: [[0, 0], [420, 0.2, 'out'], [1150, 0.2], [1600, 0, 'in-out']] } },
    perk: { dur: 700, tracks: {
      antennaLift: [[0, 0], [140, -3, 'anticip'], [300, 9, 'overshoot'], [700, 0, 'settle']],
      eyeOpen: [[0, 1], [220, 1.1, 'out'], [600, 1, 'out']],
      bodySquash: [[0, 1], [140, 0.97, 'anticip'], [300, 1.03, 'overshoot'], [600, 1, 'settle']] } },
    glance: { dur: 1800, tracks: {
      lookX: [[0, 0], [260, -0.55, 'out'], [760, -0.55], [1060, 0.5, 'in-out'], [1500, 0.5], [1800, 0, 'in-out']],
      lookY: [[0, 0], [260, -0.1, 'out'], [1500, -0.1], [1800, 0, 'in-out']] } },
    click: { dur: 1100, tracks: {
      clawL: [[0, 0], [150, -6, 'anticip'], [320, 14, 'overshoot'], [800, 10], [1100, 0, 'settle']],
      pinchL: [[320, 0], [410, 1, 'out'], [540, 0, 'out'], [630, 1, 'out'], [760, 0, 'out']] } }
  };
  var FID_NAMES = ['inspect', 'perk', 'glance', 'click'], FID_IN = 120, FID_OUT = 240;
  var HAS_DOM = typeof document !== 'undefined';
  var STYLE_RE = /<style>([\s\S]*?)<\/style>/;
  var GLYPH_FEET = { g16: [8.5, 15.5], g20: [10.6, 19.4] };
  R.setEasings(CLIPS.easings);
  var NEUTRAL = R.neutral(RIG), RANGE = {};
  RIG.params.forEach(function (d) { if (typeof d['default'] === 'number') RANGE[d.name] = [d.min, d.max]; });

  var insts = [], uid = 0, raf = 0, lastNow = 0, io = null, booted = false, rmForce = null, RM = false;

  /* ---------- small helpers ---------- */
  function now() { return root.performance && root.performance.now ? root.performance.now() : Date.now(); }
  function clamp(v, a, b) { return v < a ? a : v > b ? b : v; }
  function assign(a, b) { for (var k in b) a[k] = b[k]; return a; }
  function r3(v) { return +(+v).toFixed(3); }
  function media(q) { return !!(root.matchMedia && root.matchMedia(q).matches); }
  function computeRM() { return rmForce != null ? rmForce : media('(prefers-reduced-motion: reduce)'); }
  function rng(seed) { // mulberry32: the blink and gaze schedules are a pure function of the seed
    var a = seed >>> 0;
    return function () {
      a = (a + 0x6D2B79F5) >>> 0;
      var t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }
  function rung(size) { return size >= 96 ? 'full' : size >= 40 ? 'm56' : size >= 24 ? 'lod24' : size >= 20 ? 'g20' : 'g16'; }
  function isGlyph(r) { return r === 'g20' || r === 'g16'; }
  function mix(a, b, k) {
    var o = {};
    for (var key in b) {
      var x = a[key], y = b[key];
      o[key] = typeof x === 'number' && typeof y === 'number' ? x + (y - x) * k : (k < 0.5 && x !== undefined ? x : y);
    }
    return o;
  }
  function same(a, b) {
    if (!a || !b) return false;
    for (var k in b) {
      if (typeof b[k] === 'number' ? Math.abs(a[k] - b[k]) > 1e-3 : a[k] !== b[k]) return false;
    }
    return true;
  }

  /* ---------- schedules: seeded, so seek() is deterministic ---------- */
  function newState(seed) {
    return {
      held: {}, camera: false, opts: {},
      blink: { rng: rng(seed), end: 0, list: [] },
      gaze: { rng: rng((seed ^ 0x9E3779B9) >>> 0), list: [{ t: 0, x: 0, y: 0 }] }
    };
  }
  function blinkAt(I, t) {
    var b = I.blink, lo = BLINK.every_ms[0], hi = BLINK.every_ms[1];
    while (b.end <= t + hi) {
      b.end += lo + (hi - lo) * b.rng();
      b.list.push(b.end);
      if (b.rng() < BLINK.double_chance) b.list.push(b.end + BLINK.double_gap_ms);
    }
    for (var i = b.list.length - 1; i >= 0; i--) {
      var s = b.list[i];
      if (s <= t) return t - s < BLINK.dur ? R.sample(BLINK, t - s).eyeOpen : 1;
    }
    return 1;
  }
  function gazeAt(I, t) {
    var g = I.gaze, L = g.list, lo = GAZE.every_ms[0], hi = GAZE.every_ms[1];
    while (L[L.length - 1].t <= t) {
      var r = g.rng, prev = L[L.length - 1].t;
      L.push({ t: prev + lo + (hi - lo) * r(),
        x: GAZE.lookX[0] + (GAZE.lookX[1] - GAZE.lookX[0]) * r(),
        y: GAZE.lookY[0] + (GAZE.lookY[1] - GAZE.lookY[0]) * r() });
    }
    for (var i = L.length - 1; i > 0; i--) {
      if (L[i].t <= t) {
        var k = R.ease(GAZE.ease, clamp((t - L[i].t) / GAZE.dur_ms, 0, 1));
        return [L[i - 1].x + (L[i].x - L[i - 1].x) * k, L[i - 1].y + (L[i].y - L[i - 1].y) * k];
      }
    }
    return [0, 0];
  }

  /* ---------- poses ---------- */
  function base(I, mood, t) { // held pose, then the mood: bodySquash multiplies, numbers add, strings fill in
    var p = assign(assign({}, NEUTRAL), I.held), mv = R.sample(MOODS[mood], t);
    for (var k in mv) {
      var v = mv[k];
      if (k === 'bodySquash') p[k] *= v / NEUTRAL[k];
      else if (typeof v === 'number') p[k] += v - NEUTRAL[k];
      else if (!(k in I.held)) p[k] = v;
    }
    return p;
  }
  function limit(p) { for (var k in RANGE) p[k] = clamp(p[k], RANGE[k][0], RANGE[k][1]); return p; }
  function overlay(p, def, t) { // absolute, except the lens glow: max(mood/camera, clip), so it never blinks off mid-session
    var cv = R.sample(def, t);
    for (var k in cv) p[k] = k === 'lensGlow' ? Math.max(p[k], cv[k]) : cv[k];
    return p;
  }
  function finish(I, p, def, t, blink) {
    if (blink && !(def && (def.tracks.eyeOpen || def.tracks.joy))) p.eyeOpen *= blinkAt(I, t);
    p.lensGlow = Math.max(I.camera ? 1 : 0, p.lensGlow); // the lens never claims the camera is off while it samples
    return p;
  }
  function livePose(I) {
    var p = base(I, I.mood, I.moodT), L = I.look;
    if (I.mood === 'idle') {
      var g = gazeAt(I, I.clock);
      p.lookX += g[0] * (1 - L.w); p.lookY += g[1] * (1 - L.w);
    }
    p.lookX += L.x; p.lookY += L.y;
    limit(p);
    var fc = I.fid && I.fid.cur;
    if (fc && !I.shot) {
      var fv = R.sample(fc.def, fc.t);
      for (var k in fv) if (k !== 'lensGlow') p[k] = fv[k];
      limit(p);
    }
    if (I.shot) overlay(p, I.shot.def, I.shot.t);
    return finish(I, p, (I.shot && I.shot.def) || (fc && fc.def), I.clock, true);
  }
  function stillPose(I) {
    var p = limit(base(I, I.mood, MOODS[I.mood].key));
    if (I.shot) overlay(p, I.shot.def, I.shot.def.key);
    return finish(I, p, null, 0, false);
  }
  function seekPose(I, name, ms, blink) {
    var sd = SHOTS[name], p;
    if (MOODS[name]) {
      p = base(I, name, ms);
      if (name === 'idle') { var g = gazeAt(I, ms); p.lookX += g[0]; p.lookY += g[1]; }
      limit(p);
    } else {
      p = overlay(limit(assign(assign({}, NEUTRAL), I.held)), sd, clamp(ms, 0, sd.dur));
    }
    return finish(I, p, sd, ms, blink);
  }

  /* ---------- views: one SVG built per LOD rung; per frame only attributes change ---------- */
  function partProxy(svg) { // rig.apply() walks [data-part]; hand it cached nodes that skip unchanged writes
    var list = [];
    svg.querySelectorAll('[data-part]').forEach(function (el) {
      var name = el.getAttribute('data-part'), cache = {};
      list.push({
        getAttribute: function () { return name; },
        setAttribute: function (a, v) { v = String(v); if (cache[a] !== v) { cache[a] = v; el.setAttribute(a, v); } }
      });
    });
    return { querySelectorAll: function () { return list; } };
  }
  function makeView(r, prefix, keepStyle, size) {
    var src = r === 'g16' ? SVG.lod16 : r === 'g20' ? SVG.lod20 : r === 'lod24' ? SVG.lod24 : SVG.full;
    var m = R.prefixIds(src, prefix), d = document.createElement('div');
    d.innerHTML = keepStyle ? m : m.replace(STYLE_RE, '');
    var svg = d.firstElementChild, v = { svg: svg, rung: r };
    if (r === 'm56') svg.setAttribute('data-lod', '56');
    if (r === 'lod24') svg.setAttribute('data-lod', '28');
    svg.setAttribute('width', size); svg.setAttribute('height', size);
    if (isGlyph(r)) {
      v.root = svg.querySelector('[id$="pinch-root"]');
      v.glow = svg.querySelector('[id$="lens-glow"]');
      v.cache = {};
    } else {
      v.proxy = partProxy(svg);
    }
    return v;
  }
  function applyView(v, p, t) {
    if (!v.proxy) { // glyph: hop/squash/tilt about the feet and the lit lens; nothing else moves at 16-20 px
      var k = (v.rung === 'g16' ? 16 : 20) / 160, f = GLYPH_FEET[v.rung], sy = p.bodySquash, sx = 1 / Math.sqrt(sy);
      var tr = 'translate(0 ' + r3(p.bodyY * k) + ') rotate(' + r3(p.tilt) + ' ' + f[0] + ' ' + f[1] + ') translate(' +
        f[0] + ' ' + f[1] + ') scale(' + r3(sx) + ' ' + r3(sy) + ') translate(' + (-f[0]) + ' ' + (-f[1]) + ')';
      var op = String(r3(clamp(p.lensGlow, 0, 1)));
      if (v.cache.tr !== tr) { v.cache.tr = tr; v.root.setAttribute('transform', tr); }
      if (v.cache.op !== op) { v.cache.op = op; v.glow.setAttribute('opacity', op); }
      return;
    }
    R.apply(v.proxy, p, RIG, t);
  }
  function themeOf(I) {
    var t = I.opts.theme;
    if (t === 'dark' || t === 'light') return t;
    var a = I.wrap.parentNode && I.wrap.parentNode.closest ? I.wrap.parentNode.closest('[data-theme]') : null;
    var at = a && a.getAttribute('data-theme');
    if (at === 'dark' || at === 'light') return at;
    return media('(prefers-color-scheme: light)') ? 'light' : 'dark';
  }
  function dress(I, v) {
    var t = themeOf(I), c = v.svg.classList;
    c.toggle('on-dark', t === 'dark'); c.toggle('on-light', t === 'light'); c.toggle('rim', !!I.opts.rim);
  }

  /* ---------- global wiring (lazy, once) ---------- */
  function injectStyle() {
    if (document.getElementById('alibi-pinch-css')) return;
    var s = document.createElement('style');
    s.id = 'alibi-pinch-css';
    s.textContent = STYLE_RE.exec(SVG.full)[1] + '\n' + STYLE_RE.exec(SVG.lod20)[1] + '\n' +
      '.alibi-pinch{position:relative;display:inline-block;line-height:0;vertical-align:middle}' +
      '.alibi-pinch>svg{display:block;overflow:visible}' +
      '.alibi-pinch>.pinch-ghost{position:absolute;left:0;top:0;pointer-events:none}' +
      '.alibi-pinch.blinks [id$="eye-l"],.alibi-pinch.blinks [id$="eye-r"]{transform-box:fill-box;transform-origin:50% 0;' +
      'animation:alibi-pinch-blink 4.7s 1.3s infinite}' +
      '.alibi-pinch.blinks .pw{animation:alibi-pinch-shine 4.7s 1.3s infinite}' +
      '@keyframes alibi-pinch-blink{0%,96.6%,100%{transform:none}98.2%{transform:scaleY(.12)}}' +
      '@keyframes alibi-pinch-shine{0%,96.8%,99.6%,100%{opacity:1}97.4%,99%{opacity:0}}' +
      '@media (prefers-reduced-motion:reduce){.alibi-pinch.blinks *{animation:none!important}}';
    (document.head || document.documentElement).appendChild(s);
  }
  function boot() {
    if (booted) return;
    booted = true;
    RM = computeRM();
    injectStyle();
    document.addEventListener('visibilitychange', function () { if (!document.hidden) schedule(); });
    if (root.matchMedia) {
      var rm = root.matchMedia('(prefers-reduced-motion: reduce)'), cs = root.matchMedia('(prefers-color-scheme: light)');
      var on = function (q, fn) { if (q.addEventListener) q.addEventListener('change', fn); else if (q.addListener) q.addListener(fn); };
      on(rm, function () { if (rmForce == null) setRM(); });
      on(cs, rethemeAll);
    }
    if (root.MutationObserver) {
      new MutationObserver(rethemeAll).observe(document.documentElement, { attributes: true, subtree: true, attributeFilter: ['data-theme'] });
    }
    if (root.IntersectionObserver) {
      io = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          for (var i = 0; i < insts.length; i++) if (insts[i].wrap === e.target) insts[i].onscreen = e.isIntersecting;
        });
        schedule();
      }, { rootMargin: '64px' });
    }
  }
  function rethemeAll() { insts.forEach(function (I) { dress(I, I.view); }); }
  function setRM() { RM = computeRM(); insts.forEach(function (I) { refresh(I, true); }); }

  /* ---------- the shared loop ---------- */
  function still(I) { return !!I.opts.still || RM || I.glyph; }
  function ticking(I) { return !I.dead && I.mode === 'live' && !still(I) && I.onscreen && !I.rested; }
  function schedule() {
    if (raf || !HAS_DOM || document.hidden) return;
    for (var i = 0; i < insts.length; i++) {
      if (ticking(insts[i])) { lastNow = 0; raf = root.requestAnimationFrame(frame); return; }
    }
  }
  function frame(t) {
    raf = 0;
    if (document.hidden) return;
    var dt = lastNow ? clamp(t - lastNow, 0, 64) : 16.7, more = false;
    lastNow = t;
    insts.slice().forEach(function (I) {
      if (!ticking(I)) return;
      step(I, dt);
      if (ticking(I)) more = true;
    });
    if (more) raf = root.requestAnimationFrame(frame);
  }
  function step(I, dt) {
    I.clock += dt; I.moodT += dt;
    var L = I.look, a = 1 - Math.exp(-dt / 90);
    L.x += (L.tx - L.x) * a; L.y += (L.ty - L.y) * a; L.w += ((L.on ? 1 : 0) - L.w) * a;
    if (I.shot) { I.shot.t += dt; if (I.shot.t >= I.shot.def.dur) endShot(I); }
    if (!I.resting && !I.shot && !I.xf && !I.opts.ambient && now() - I.input > REST) { I.resting = true; startXf(I, REST_MS, 'in-out'); }
    if (!I.resting) stepFidget(I);
    var p = I.resting ? stillPose(I) : livePose(I);
    if (I.xf) {
      var k = (I.clock - I.xf.t0) / I.xf.dur;
      if (k >= 1) I.xf = null; else p = mix(I.xf.from, p, R.ease(I.xf.ease, k));
    }
    if (I.resting && !I.xf) I.rested = true;
    render(I, p, I.clock);
  }
  function render(I, p, t) { applyView(I.view, p, t); I.last = p; I.lastT = t; }
  function startXf(I, dur, ease) { if (I.last) I.xf = { from: I.last, t0: I.clock, dur: dur, ease: ease }; }

  /* ---------- ambient fidgets: seeded, on the instance clock (which only runs while it is visible) ---------- */
  function quietLobster() { try { return !!(root.localStorage && root.localStorage.getItem('alibi.quiet') === '1'); } catch (e) { return false; } }
  function fidgetsOn(I) { return !!I.opts.ambient && I.mood === 'idle' && !still(I) && !quietLobster(); }
  function nextFidget(F) { // a seeded shuffle of the four, never the same one twice in a row
    if (!F.order.length) {
      var a = FID_NAMES.slice();
      for (var i = a.length - 1; i > 0; i--) { var j = Math.floor(F.rng() * (i + 1)), t = a[i]; a[i] = a[j]; a[j] = t; }
      if (a[0] === F.last) a.push(a.shift());
      F.order = a;
    }
    return F.order.shift();
  }
  function stepFidget(I) {
    var F = I.fid;
    if (!F) return;
    if (F.cur) {
      F.cur.t = I.clock - F.cur.t0;
      if (I.shot) { F.cur = null; return; }                     // a clip pre-empts it; the clip's blend-in carries the fade
      if (F.cur.t >= F.cur.def.dur || !fidgetsOn(I)) endFidget(I, true);
      return;
    }
    if (I.shot || I.clock < F.next || !fidgetsOn(I)) return;
    var name = nextFidget(F);
    F.last = name;
    F.cur = { name: name, def: FIDGETS[name], t0: I.clock, t: 0 };
    F.next = I.clock + 14000 + 14000 * F.rng();
    startXf(I, FID_IN, 'in-out');
  }
  function endFidget(I, blend) {
    if (!I.fid || !I.fid.cur) return;
    I.fid.cur = null;
    if (blend && !still(I)) startXf(I, FID_OUT, 'in-out');
  }

  /* ---------- still mode: key poses, crossfaded through a ghost copy (no rAF) ---------- */
  function stillShow(I, fade) {
    var p = stillPose(I), t = MOODS[I.mood].key;
    if (fade && I.last && !same(I.last, p)) ghost(I);
    render(I, p, t);
  }
  function ghost(I) {
    var v = makeView(I.rung, 'pinch' + I.id + 'g' + (++uid) + '-', false, I.size);
    dress(I, v);
    applyView(v, I.last, I.lastT);
    v.svg.classList.add('pinch-ghost');
    v.svg.style.opacity = '1';
    I.wrap.appendChild(v.svg);
    v.svg.getBoundingClientRect();
    v.svg.style.transition = 'opacity ' + FADE_MS + 'ms linear';
    v.svg.style.opacity = '0';
    setTimeout(function () { if (v.svg.parentNode) v.svg.parentNode.removeChild(v.svg); }, FADE_MS + 60);
  }

  /* ---------- instance lifecycle ---------- */
  function build(I) {
    var r = rung(I.size);
    if (I.view && I.view.svg.parentNode) I.view.svg.parentNode.removeChild(I.view.svg);
    I.rung = r; I.glyph = isGlyph(r);
    I.view = makeView(r, 'pinch' + I.id + '-', false, I.size);
    dress(I, I.view);
    I.wrap.style.width = I.wrap.style.height = I.size + 'px';
    I.wrap.insertBefore(I.view.svg, I.wrap.firstChild);
    if (I.last) applyView(I.view, I.last, I.lastT);
  }
  function refresh(I, fade) {
    var s = still(I);
    I.wrap.classList.toggle('blinks', I.rung === 'g20' && !RM && !I.opts.still);
    if (I.wasStill !== undefined && s !== I.wasStill && I.shot) { // a clip never straddles live and still
      var sh = I.shot; I.shot = null; clearTimeout(I.timer); sh.resolve(true);
    }
    I.wasStill = s;
    if (I.mode === 'seek') return;
    if (s) { stillShow(I, fade); return; }
    if (!I.last) render(I, livePose(I), I.clock);
    else if (fade) { I.rested = I.resting = false; startXf(I, WAKE_MS, 'in-out'); }
    schedule();
  }
  function wake(I) { // any input: leave seek or rest, restart the 2 min idle timer
    I.input = now();
    var wasSeek = I.mode === 'seek', wasRest = I.resting;
    I.mode = 'live'; I.resting = I.rested = false;
    if (still(I)) { if (wasSeek) stillShow(I, true); return; }
    if (wasSeek || wasRest) startXf(I, WAKE_MS, 'in-out');
    schedule();
  }
  function setMood(I, m) {
    if (!MOODS[m]) return;
    wake(I);
    if (m === I.mood) return;
    I.mood = m; I.moodT = 0;
    if (still(I)) stillShow(I, true); else startXf(I, MOOD_MS, 'in-out');
  }
  function play(I, name, o) {
    o = o || {};
    var def = SHOTS[name];
    return new Promise(function (resolve) {
      if (!def || I.dead) { resolve(false); return; }
      var t = now(), force = !!o.force;
      if (!force) {
        if (I.shot && def.priority <= I.shot.def.priority) { resolve(false); return; }
        if (!I.shot && t - I.lastShotAt < COOLDOWN && def.priority <= I.lastShotPrio) { resolve(false); return; }
        if (name === 'sideeye' && I.sideeyes >= POL.max_sideeye_per_session) { resolve(false); return; }
      }
      wake(I);
      var preempt = !!I.shot;
      if (I.shot) { clearTimeout(I.timer); I.shot.resolve(false); }
      if (name === 'sideeye') I.sideeyes++;
      I.lastShotAt = t; I.lastShotPrio = def.priority;
      I.shot = { name: name, def: def, t: 0, resolve: resolve, chain: o.chain === false ? null : POL.chain[name] };
      if (still(I)) { stillShow(I, true); I.timer = setTimeout(function () { endShot(I); }, def.dur); }
      else { startXf(I, preempt ? WAKE_MS : POL.blend_in_ms, 'in-out'); schedule(); } // a pre-empted pose can be far away
    });
  }
  function endShot(I) {
    var s = I.shot;
    if (!s) return;
    I.shot = null; clearTimeout(I.timer);
    if (I.dead) { s.resolve(false); return; }
    if (still(I)) stillShow(I, true); else startXf(I, POL.blend_out_ms, 'in-out');
    if (s.chain) play(I, s.chain, { force: true, chain: false }).then(s.resolve); else s.resolve(true);
  }

  function mount(el, opts) {
    if (!HAS_DOM || !el) throw new Error('AlibiPinch.mount needs a DOM element');
    opts = opts || {};
    boot();
    var id = ++uid;
    var I = assign(newState(opts.seed != null ? opts.seed : id * 7919 + 17), {
      id: id, opts: { still: !!opts.still, theme: opts.theme || 'auto', rim: !!opts.rim, ambient: !!opts.ambient },
      size: opts.size || 96, mood: MOODS[opts.mood] ? opts.mood : 'idle',
      shot: null, xf: null, last: null, lastT: 0, clock: 0, moodT: 0, mode: 'live', timer: 0,
      look: { x: 0, y: 0, tx: 0, ty: 0, w: 0, on: false }, onscreen: true, resting: false, rested: false, input: now(),
      lastShotAt: -Infinity, lastShotPrio: -1, sideeyes: 0, dead: false
    });
    var fr = rng(((opts.seed != null ? opts.seed : id * 7919 + 17) ^ 0x5BD1E995) >>> 0);
    I.fid = { rng: fr, next: 6000 + 4000 * fr(), cur: null, order: [], last: null };
    I.wrap = document.createElement('span');
    I.wrap.className = 'alibi-pinch';
    el.appendChild(I.wrap);
    build(I);
    insts.push(I);
    if (io) io.observe(I.wrap);
    refresh(I, false);
    return api(I);
  }

  function api(I) {
    var o = {
      el: I.wrap,
      set: function (mood) { if (!I.dead) setMood(I, mood); return o; },
      play: function (clip, opts) { return play(I, clip, opts); },
      lookAt: function (x, y) {
        if (I.dead) return o;
        var L = I.look;
        if (x == null) { L.on = false; L.tx = L.ty = 0; } else { L.on = true; L.tx = clamp(+x || 0, -1, 1); L.ty = clamp(+y || 0, -1, 1); }
        if (!still(I)) wake(I);
        return o;
      },
      seek: function (name, ms) {
        if (I.dead || (!MOODS[name] && !SHOTS[name])) return o;
        ms = +ms || 0;
        I.mode = 'seek'; I.xf = null;
        render(I, seekPose(I, name, ms, !I.opts.still && !I.glyph), ms);
        return o;
      },
      resume: function () { if (!I.dead) wake(I); return o; },
      setSize: function (px) {
        if (I.dead || !(px > 0) || px === I.size) return o;
        var old = I.rung;
        I.size = px;
        if (rung(px) !== old) { build(I); refresh(I, false); return o; }
        I.view.svg.setAttribute('width', px); I.view.svg.setAttribute('height', px);
        I.wrap.style.width = I.wrap.style.height = px + 'px';
        return o;
      },
      camera: function (on) {
        if (I.dead || I.camera === !!on) return o;
        I.camera = !!on;
        if (still(I) && I.mode !== 'seek') stillShow(I, true); else wake(I);
        return o;
      },
      pose: function (params) {
        if (I.dead) return o;
        I.held = {};
        for (var k in params || {}) if (k in NEUTRAL) I.held[k] = params[k];
        if (still(I)) { if (I.mode !== 'seek') stillShow(I, false); } else wake(I);
        return o;
      },
      theme: function (theme, rim) { // 'auto'|'dark'|'light', and the opt-in rim on dark
        if (I.dead) return o;
        if (theme) I.opts.theme = theme;
        if (rim != null) I.opts.rim = !!rim;
        dress(I, I.view);
        return o;
      },
      frame: function () { return I.last ? assign({}, I.last) : null; }, // the last rendered param vector
      state: function () {
        return { mood: I.mood, clip: I.shot ? I.shot.name : null, rung: I.rung, size: I.size, camera: I.camera,
          mode: I.dead ? 'destroyed' : I.mode === 'seek' ? 'seek' : still(I) ? 'still' : I.rested ? 'resting' : 'live',
          cooldownLeft: Math.max(0, Math.round(COOLDOWN - (now() - I.lastShotAt))), sideeyes: I.sideeyes,
          ambient: !!I.opts.ambient, fidget: I.fid && I.fid.cur ? I.fid.cur.name : null };
      },
      ambient: function (on) {
        if (I.dead) return o;
        I.opts.ambient = !!on;
        if (!on) endFidget(I, true); else if (!still(I)) wake(I);
        return o;
      },
      destroy: function () {
        if (I.dead) return;
        I.dead = true;
        clearTimeout(I.timer);
        if (I.shot) { I.shot.resolve(false); I.shot = null; }
        if (io) io.unobserve(I.wrap);
        var i = insts.indexOf(I);
        if (i >= 0) insts.splice(i, 1);
        if (I.wrap.parentNode) I.wrap.parentNode.removeChild(I.wrap);
      }
    };
    return o;
  }

  function svg(o) {
    if (!o || !HAS_DOM) return SVG.full;
    var name = o.clip || o.mood || 'idle';
    if (!MOODS[name] && !SHOTS[name]) name = 'idle';
    var def = MOODS[name] || SHOTS[name], size = o.size || 160, r = rung(size);
    var S = newState(o.seed != null ? o.seed : 1);
    S.camera = !!o.camera;
    var v = makeView(r, 'pinchs' + (++uid) + '-', true, size);
    applyView(v, seekPose(S, name, o.ms == null ? def.key : +o.ms, false), o.ms == null ? def.key : +o.ms);
    if (o.theme === 'dark' || o.theme === 'light') v.svg.classList.add('on-' + o.theme);
    if (o.rim) v.svg.classList.add('rim');
    return v.svg.outerHTML;
  }

  root.AlibiPinch = {
    version: '1.0.0',
    mount: mount,
    svg: svg,
    moods: Object.keys(MOODS),
    clips: Object.keys(SHOTS),
    params: RIG.params.map(function (d) { return assign({}, d); }),
    duration: function (name) { var d = MOODS[name] || SHOTS[name]; return d ? d.dur : 0; },
    keyFrame: function (name) { var d = MOODS[name] || SHOTS[name]; return d ? d.key : 0; },
    keyTimes: function (name) {
      var d = MOODS[name] || SHOTS[name], seen = {};
      if (!d) return [];
      for (var k in d.tracks) d.tracks[k].forEach(function (f) { seen[f[0]] = 1; });
      return Object.keys(seen).map(Number).sort(function (a, b) { return a - b; });
    },
    reducedMotion: function (v) {
      if (arguments.length) { rmForce = v == null ? null : !!v; if (booted) setRM(); else RM = computeRM(); }
      return booted ? RM : computeRM();
    }
  };
})(typeof window !== 'undefined' ? window : globalThis);
