#!/usr/bin/env python3
"""Demo title/end cards, Pinch stills and the web "bad days" takes (IMPLEMENTATION §7 L6 K6, DEMO.md §2 and W1).

    python3 docs/design/demo/cards/record.py                       # demo/clips/00-title.mp4 + 99-end.mp4 + stills
    python3 docs/design/demo/cards/record.py --witness nvidia-build # end-card witness line (DEMO.md §3)
    python3 docs/design/demo/cards/record.py --only title|end|stills|data
    python3 docs/design/demo/cards/record.py --stage verdict_partial,verdict_slacked [--base http://127.0.0.1:8775]

Cards: 1920x1080, exactly 4.0 s at 60 fps (240 frames). The pages run on a seekable clock (`Card.seek(ms)`), so
every frame is a crisp Playwright screenshot at 1280x720 CSS px x1.5 piped into ffmpeg; nothing depends on how fast
this Mac renders. --stage records the live dashboard's verdict reveal (not seekable) with Playwright's video
recorder, trimmed to 4.0 s, 960x1080.

pinch-data.js (rig.json, clips.json, pinch.svg as one script) is rebuilt from docs/design/pinch/ on every run, so the
cards work from file:// and never drift from the generator. When docs/design/pinch/pinch.js (the AlibiPinch
engine) exists, the cards load it too and use its markup; the deterministic rig drives the motion either way.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys
import time

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[3]
PINCH = ROOT / "docs/design/pinch"
CLIPS_OUT = ROOT / "demo/clips"
FPS, SECONDS = 60, 4.0
W, H, SCALE = 1280, 720, 1.5                      # CSS px x device scale = 1920x1080

WITNESS = {                                       # DEMO.md §3, end-card line
    "apple": "Frames are judged on-device by Apple Vision.",
    "nvidia-local": "NVIDIA VLM on my own hardware. Frames never leave my network.",
    "nvidia-build": "Frames are judged by an NVIDIA VLM on NVIDIA Build.",
}


def build_data() -> pathlib.Path:
    rig = json.loads((PINCH / "rig.json").read_text())
    clips = json.loads((PINCH / "clips.json").read_text())
    svg = (PINCH / "pinch.svg").read_text()
    engine = (PINCH / "pinch.js").exists()
    tag = "  // lint-ok generated from docs/design/pinch by record.py (rig data, not UI colour or motion)"
    lines = ["/* Generated by docs/design/demo/cards/record.py from docs/design/pinch/. Do not edit. */",
             "window.PINCH_DATA = {" + tag,
             f"  engine: {json.dumps(engine)}," + tag,
             f"  rig: {json.dumps(rig, separators=(',', ':'))}," + tag,
             f"  clips: {json.dumps(clips, separators=(',', ':'))}," + tag,
             f"  svg: {json.dumps(svg)}" + tag,
             "};"]
    out = HERE / "pinch-data.js"
    out.write_text("\n".join(lines) + "\n")
    return out


def page_errors(pg, errs: list) -> None:
    pg.on("console", lambda m: errs.append(f"console.{m.type}: {m.text}") if m.type in ("error", "warning") else None)
    pg.on("pageerror", lambda e: errs.append(f"pageerror: {e}"))


def record_card(p, name: str, out: pathlib.Path, query: str = "") -> None:
    url = (HERE / f"{name}.html").as_uri() + "?record=1" + (f"&{query}" if query else "")
    b = p.chromium.launch()
    ctx = b.new_context(viewport={"width": W, "height": H}, device_scale_factor=SCALE, color_scheme="dark")
    pg = ctx.new_page()
    errs: list = []
    page_errors(pg, errs)
    pg.goto(url)
    pg.wait_for_function("window.Card && window.Card.ready === true", timeout=15000)
    pg.evaluate("document.fonts.ready.then(() => true)")
    n = int(FPS * SECONDS)
    out.parent.mkdir(parents=True, exist_ok=True)
    ff = subprocess.Popen(["ffmpeg", "-loglevel", "error", "-y", "-f", "image2pipe", "-framerate", str(FPS),
                           "-i", "-", "-frames:v", str(n), "-c:v", "libx264", "-preset", "slow", "-crf", "14",
                           "-pix_fmt", "yuv420p", "-movflags", "+faststart", str(out)], stdin=subprocess.PIPE)
    t0 = time.time()
    for i in range(n):
        pg.evaluate(f"window.Card.seek({i * 1000 / FPS:.4f})")
        ff.stdin.write(pg.screenshot(type="png"))
    ff.stdin.close()
    if ff.wait() != 0:
        sys.exit(f"record: ffmpeg failed for {out}")
    b.close()
    for e in errs:
        print(e, file=sys.stderr)
    print(f"wrote {out.relative_to(ROOT)} ({n} frames, {time.time() - t0:.0f} s)")


def stills(p, size: int = 512) -> None:
    b = p.chromium.launch()
    for clip in ("celebrate", "partial", "supportive", "hello"):
        ctx = b.new_context(viewport={"width": size, "height": size}, device_scale_factor=1, color_scheme="dark")
        pg = ctx.new_page()
        errs: list = []
        page_errors(pg, errs)
        pg.goto((HERE / "still.html").as_uri() + f"?clip={clip}&size={size}")
        pg.wait_for_function("window.Card && window.Card.ready === true", timeout=15000)
        out = HERE / f"pinch-{clip}-{size}.png"
        pg.screenshot(path=str(out), omit_background=True)
        ctx.close()
        for e in errs:
            print(e, file=sys.stderr)
        print(f"wrote {out.relative_to(ROOT)}")
    b.close()


def record_stage(p, names: list[str], base: str) -> None:
    """Live dashboard verdict reveal from a ?stage= fixture (DEMO.md take W1): real-time video, trimmed to 4.0 s."""
    tmp = pathlib.Path("/tmp/alibi-record-stage")
    tmp.mkdir(exist_ok=True)
    for i, name in enumerate(names):
        b = p.chromium.launch()
        ctx = b.new_context(viewport={"width": 960, "height": 1080}, device_scale_factor=1, color_scheme="dark",
                            record_video_dir=str(tmp), record_video_size={"width": 960, "height": 1080})
        pg = ctx.new_page()                                   # the video starts with the page
        t_open = time.time()
        errs: list = []
        page_errors(pg, errs)
        pg.goto(f"{base.rstrip('/')}/?stage={name}&moment=verdict")
        t_load = time.time() - t_open
        pg.wait_for_timeout(int(SECONDS * 1000) + 600)
        video = pg.video.path()
        ctx.close()
        b.close()
        label = name.replace("verdict_", "")
        out = CLIPS_OUT / f"12{'abcdefgh'[i]}-{label}.mp4"
        subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-ss", f"{max(0.0, t_load):.2f}", "-i", str(video),
                        "-vf", f"fps={FPS},tpad=stop_mode=clone:stop_duration=1", "-frames:v", str(int(FPS * SECONDS)),
                        "-c:v", "libx264", "-crf", "16", "-pix_fmt", "yuv420p",
                        "-an", str(out)], check=True)
        for e in errs:
            print(e, file=sys.stderr)
        print(f"wrote {out.relative_to(ROOT)}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Render the demo cards, Pinch stills and web verdict takes.")
    ap.add_argument("--only", choices=["title", "end", "stills", "data"])
    ap.add_argument("--witness", choices=sorted(WITNESS), default="apple", help="end-card line, from ./alibi.sh status")
    ap.add_argument("--url", default="github.com/Harrishayy/nvidia_habits", help="end-card repo or submission URL")
    ap.add_argument("--stage", help="comma list of fixture names to record from the dashboard's ?stage= mode")
    ap.add_argument("--base", default="http://127.0.0.1:8775", help="lab server for --stage")
    a = ap.parse_args()

    data = build_data()
    print(f"wrote {data.relative_to(ROOT)}")
    if a.only == "data":
        return
    from playwright.sync_api import sync_playwright
    from urllib.parse import urlencode
    with sync_playwright() as p:
        if a.stage:
            record_stage(p, [s.strip() for s in a.stage.split(",") if s.strip()], a.base)
            return
        if a.only in (None, "title"):
            record_card(p, "title", CLIPS_OUT / "00-title.mp4")
        if a.only in (None, "end"):
            record_card(p, "end", CLIPS_OUT / "99-end.mp4", urlencode({"witness": WITNESS[a.witness], "url": a.url}))
        if a.only in (None, "stills"):
            stills(p)


if __name__ == "__main__":
    main()
